DFE-Digital/Dfe.Academies.External

- specification/ApplyToBecomeAnAcademy/01 Start Feature/05 What Is Your Role Page.md
A few edits to these gherkins:
* use page name instead of page title
* deleted a few words that don't add any clarity
* eliminated ANDs in the WHEN clauses
> AB#97101 What Is Your Role Page - use page name instead of page title

- Dfe.Academies.External.Web/Pages/Accessibility.cshtml
- Dfe.Academies.External.Web/Pages/Cookies.cshtml
- Dfe.Academies.External.Web/Pages/Cookies.cshtml.cs
- Dfe.Academies.External.Web/Pages/Index.cshtml
- Dfe.Academies.External.Web/Pages/Shared/_Footer.cshtml
- Dfe.Academies.External.Web/Pages/Shared/_Layout.cshtml
- Dfe.Academies.External.Web/Pages/Terms.cshtml
- Dfe.Academies.External.Web/Program.cs
Added pages:
* Accessibility (copied from current A2B External)
* Cookies (blank for now)
* Terms (copied from current A2B External)
> AB#92475 Page Header & Footer - add linked static pages with page titles

- Dfe.Academies.External.Web/appsettings.json
Adding default config to the appsettings.json so that the dev environment doesn't fail
> Add default Academies API config

- Dfe.Academies.External.Web/appsettings.Development.json
These are for Authorization checks on organisation or service membership that we don't do
> Remove DfE Sign-in urls from appsettings.Development.json

- Dfe.Academies.External.Web.UnitTest/Factories/ConversionApplicationTestDataFactory.cs
- Dfe.Academies.External.Web/Models/ConversionApplication.cs
- Dfe.Academies.External.Web/Pages/WhatIsYourRole.cshtml.cs
remove contributor properties from application model to convert to ConversionApplicationContributor object as per API specification
Role properties no longer exist at application model level (only put here temporarily while dev'ing UI). So moved setting of these properties into the ConversionApplicationContributor object as per API specification
n/a
1. Run Unit Tests
2. Run the application, go through wizard to ensure everything working as expected i.e. when you input role / other role ensure app doesn't blow up
n/a
> remove contributor properties from application model - bring in line with API

- Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationConversionTargetDateModelTests.cs
- Dfe.Academies.External.Web/Constants/FieldConstants.cs
- Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
- Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml
- Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
Fix bespoke datepicker data binding issues & getting values on post
1. When submitting conversion target date page, the target date input got lost
2. Also, if an incorrect data was submitted this was lost on submit
run Unit tests - as change made to resilient request provider - although CI / CD does this for you
Test application by:-
a) log in
b) go into an existing application from the pending applications section
c) click 'about the conversion' on application overview page
d) click 'start section' on date for conversion on school overview page
e) select 'yes', input an incorrect data e.g. 30/02/2022 and a reason
f) press 'save and return to overview'
g) you will receive a  validation warning, but, the date will be re-populated
n/a
> Bug conversion date binding

- Dfe.Academies.External.Web.UnitTest/Pages/School/LandAndBuildingsModelTests.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml
- Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml.cs
- Dfe.Academies.External.Web/ViewModels/QuestionAndAnswerConstants.cs
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105405?McasTsid=26110
If input incorrect Works Planned Date validation error shown and incorrect date kept
1. When submitting Works Planned Date page, the date input value got lost
2. Also, if an incorrect data was submitted this was lost on submit
3. Also fixed land & buildings summary page bug when no land & building data existed against application
4. Also, set status of 'Heading' on land & buildings summary page
1) run Unit tests - as change made to resilient request provider - although CI / CD does this for you
2) Test application by:-
a) log in
b) go into an existing application from the pending applications section
c) click 'land and buildings' on application overview page
d) click 'start …
> 105405 datepicker fix land and buildings page

- Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml
- Dfe.Academies.External.Web/Pages/School/PupilNumbers.cshtml.cs
Following bug tickets:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105949?McasTsid=26110
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105740?McasTsid=26110
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/106008?McasTsid=26110
- Missing wording added to LandAndBuildings page
- Amended validation warning text on ApplicationSchoolConsultation page
- Amended validation warning text on future pupil numbers page
1. Browse to land & buildings page, additional text about shared facilities is missing
2. validation warning doesn't make sense on school consultation page
3. validation warning doesn't make sense on future pupil numbers page
1. Browse to land & …
> 106008 missing text land and buildings

- Dfe.Academies.External.Web/Extensions/BoolEnumExtension.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultationSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/PupilNumbersSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
- Dfe.Academies.External.Web/Pages/Shared/_SchoolConversionComponentPartial.cshtml
- Dfe.Academies.External.Web/ViewModels/SchoolQuestionAndAnswerViewModel.cs
Bug fix for this bug:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105744?McasTsid=26110
On the land & buildings summary page when no land & buildings data exists the page shows data i.e. PlannedBuildingWorks = No
1. Browse to land & buildings summary page on an application with no data
2. Browse to future pupil number summary page on an application with no data
3. Browse to pre-opening support grant summary page on an application with no data
4. Browse to school overview page / about the conversion on an application with no data
1. Browse to land & buildings summary page on an application with no data screen should say 'not entered' against the questions. Also, should hide any sub questions not filled in.
2. Browse to future pupil number …
> Summary Page - not handling null values correctly

- Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml
- Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml
- Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml
Bug ticket number:-
TBC
The yes / no select options on the following page are the wrong way around:-
ApplicationChangeSchoolName
ApplicationConversionTargetDate
ApplicationSchoolConsultation
LandAndBuildings
1. Go into ApplicationChangeSchoolName - option will be no then yes
2. Go into ApplicationConversionTargetDate - option will be no then yes
3. Go into ApplicationSchoolConsultation - option will be no then yes
4. Go into LandAndBuildings- option will be no then yes
1. Go into ApplicationChangeSchoolName - option will be yes then no
2. Go into ApplicationConversionTargetDate - option will be yes then no
3. Go into ApplicationSchoolConsultation - option will be yes then no
4. Go into LandAndBuildings- option will be yes then no
n/a
> order enum values to fix upside/down bug

- Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml
- Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml
- Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml
- Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml.cs
Bugs (no ticket exists - sorry)
1) Amend all incorrect date validation messages to be - 'You must input a valid date' on financial pages
2) Amend selected option validation message to be - "You must select an option" on financial pages as per UAC
3) Amend 'Plane' - > 'Plan ' on financial pages
4) User Story #102482 – Conversion target date page - c)	If a user inputs an incorrect date - validation message is wrong as per UAC
5) User Story #102482 – Conversion target date page - In scenario 4 both messages state “You must explain why you want to convert on this date”.  The former message at the top in the box should probably read “You must provide details” as per Acceptance Criteria 
4 Issues as per above fixes
1. Go to financial pages, see typos
2. Go to financial pages, don't select …
> Bugs from dan mk1

- Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml
- Dfe.Academies.External.Web/Pages/Shared/_SchoolConversionComponentPartial.cshtml
Bugs as below from meeting on 28/09/2022 (ticket numbers below):-
1) Contact Details page - “Who is the main contact for the conversion?” text missing as seen in the design
2) Summary pages - all, but mainly land and buildings one - sub question heading text should be light grey as per as-is
3) Land and buildings summary page - WorksPlannedDate showing when it's coming back from API as 01/01/1900
107715 - v1.5: Contact Details Page: “Who is the main contact for the conversion?” Text Missing Above Radio Buttons
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107725?McasTsid=26110
1) Contact Details page - “Who is the main contact for the conversion?” text missing as seen in the design
2) Summary pages - all, but mainly land and buildings one - sub …
> Bugs from dan mk2

- Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml
- Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml
- Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml
Resolve following bug:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107832?McasTsid=26110
Buttons have wrong text, should have right text
1. Go to Previous financial year page - button has wrong text
2. Go to Current financial year page - button has wrong text
3. Go to Next financial year page - button has wrong text
1. Go to Previous financial year page - button has right text
2. Go to Current financial year page - button has right text
3. Go to Next financial year page - button has right text
n/a
> 107832 - amended button text to - 'Save and continue'

- Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrant.cshtml
Resolve following bug:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107086?McasTsid=26110
Pre-opening support grant page was missing some text (legend)
1. Go to pre-support grant page and observe missing legend / text
1. Go to pre-support grant page and observe correct legend / text
n/a
> 107086 pre opening support grant page

- Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml
- Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml
- Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml.cs
Fin investigations bugs:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107923?McasTsid=26110
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107925?McasTsid=26110
Conversion target date bug:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107886?McasTsid=26110
Text wrong on financial investigations page
Navigation wrong on financial investigations page on save
Button text wrong on Conversion target date page
Text wrong on financial investigations page
Navigation wrong on financial investigations page on save
Button text wrong on Conversion target date page
Text right on financial investigations page
Navigation right on financial investigations page on save …
> Bugs fin investigations page and conversion target date

- Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs
bug ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107147?McasTsid=26110
When pressing save on change school name page user should be re-directed to 'About the conversion' page and save button was sometimes crashing
1.When pressing save on change school name page user should be re-directed to 'About the conversion' page
2. save button was sometimes crashing
1. When pressing save on change school name page user should be re-directed to 'About the conversion' page
2. Go in and out of change school name, change from yes / no. Testing both options to ensure save doesn't crash
n/a
> bug - fix save button to nav to right page and fix exception

- Dfe.Academies.External.Web.UnitTest/ExampleJsonResponses/getApplicationResponse.json
- Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
- Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceTests.cs
- Dfe.Academies.External.Web/Models/SchoolApplyingToConvert.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrant.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultationSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/Declaration.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/DeclarationSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml.cs
- Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
- Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
- Dfe.Academies.External.Web/ViewModels/DeclarationSummaryHeadingViewModel.cs
Wire up API endpoint into following pages:-
Declaration Page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104226?McasTsid=26110
Declaration Summary Page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104225?McasTsid=26110
Financial Investigations Page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/103592?McasTsid=26110
Finance Review Page:-
TBC
Consultation Details Page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/103421?McasTsid=26110
Consultation Summary Page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/103420?McasTsid=26110
++ these bugs while I was here …
> additional JSON properties for 3 sections put into API

- Dfe.Academies.External.Web/Program.cs
See:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108774?McasTsid=26110
Dollars showing on dev URL instead of £ for currency symbol
1. Browse to loans page on dev test URL and see $
1. Browse to loans page on dev test URL and see £
n/a
> default request culture = UK

- Dfe.Academies.External.Web/Program.cs
See:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108774?McasTsid=26110
Dollars showing on dev URL instead of £ for currency symbol
1. Browse to loans page on dev test URL and see $
1. Browse to loans page on dev test URL and see £
n/a
> Another app culture tweak

- Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml.cs
Resolves:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108900?McasTsid=26110
Finance Review page - next financial year summary shows next financial year data
1. Go to Finance Review page - next financial year summary shows wrong data
1. Finance Review page - next financial year summary shows next financial year data
n/a
> Finance Review page - next financial year summary shows next financial year data

- Dfe.Academies.External.Web/Pages/School/Loans.cshtml
Resolves:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108900?McasTsid=26110
Finance Review page - next financial year summary shows next financial year data
1. Go to Finance Review page - next financial year summary shows wrong data
1. Finance Review page - next financial year summary shows next financial year data
n/a
> hard coded currency symbol as culture still not working

- Dfe.Academies.External.Web/Pages/School/Declaration.cshtml.cs
See bug:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108857?McasTsid=26110
1. User should be forced to tick box checkboxes on declaration page. But isn't
1. User should be forced to tick box checkboxes on declaration page. But isn't
1. User should be forced to tick box checkboxes on declaration page. Now is
n/a
> checkbox validation on declaration page incorrect

- Dfe.Academies.External.Web/Pages/WhatIsYourRole.cshtml
Resolves [109323](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=109323)
The text label on the WhatIsYourRole page is missing
1. Follow the steps on the ticket
2. Create an application
3. Select join a MAT
4. Does the text appear on the role
1.
2.
3.
4.
> Added missing text field and margin marker

- Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
fix this issue:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/109819?McasTsid=26110
Selected school against application isn't showing on About the conversion page
1. Selected school against application isn't showing on About the conversion page
1. Selected school against application shows on About the conversion page
n/a
> v1.5: Name of School Fails to Return On About the conversion page

- Dfe.Academies.External.Web/Pages/ApplicationAccessException.cshtml
- Dfe.Academies.External.Web/Pages/ApplicationAccessException.cshtml.cs
- Dfe.Academies.External.Web/Pages/Error.cshtml
- Dfe.Academies.External.Web/Pages/NotFound.cshtml
New page and layout as per ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108806?McasTsid=26110
We need to put some code into each page to check whether logged on user has access to the application they are trying to view (they're setup as a contributor). If this check fails, this page should be shown (that code to come later).
n/a
1. Browse to https://localhost:44350/application-access-exception to test
n/a
> 108806 access denied page styling

- Dfe.Academies.External.Web.UnitTest/Dfe.Academies.External.Web.UnitTest.csproj
- Dfe.Academies.External.Web.UnitTest/ExampleJsonResponses/getApplicationResponse.json
- Dfe.Academies.External.Web.UnitTest/Models/ExistingTrustTests.cs
- Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
- Dfe.Academies.External.Web/Models/ConversionApplication.cs
- Dfe.Academies.External.Web/Models/ExistingTrust.cs
- Dfe.Academies.External.Web/Models/NewTrust.cs
- Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Wire up select trust page up to API as per ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104124?McasTsid=26110
1) Selected trust should be persisted in database
2) selected trust name should show on application overview page
n/a
1. go to application overview / press 'add trust' button / search & select trust, press 'Save and continue' trust is persisted
2. select trust name is shown on application overview and  'add trust' button disappears
n/a
> 105461 wire up add trust page to api

- Dfe.Academies.External.Web/Pages/School/Leases.cshtml
See bug:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/111024?McasTsid=26110
Currency symbol on leases summary page
1. Go to leases summary page no currency symbol on amount
1. Go to leases summary page currency symbol on amount
n/a
> add currency symbol

- Dfe.Academies.External.Web/Pages/Shared/_Footer.cshtml
see below ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108927?McasTsid=26110
On every page there is a privacy link at the bottom of the page
n/a
1. Open application - should have privacy link at the bottom and this should open privacy page
2. Login application - should have privacy link at the bottom and this should open privacy page
n/a
> add privacy link to footer

- Dfe.Academies.External.Web/Pages/Privacy.cshtml
Content changes for this ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/64069
content on privacy notice page should match this:-
https://www.figma.com/file/xqCVptyOcxauUXNum87EBG/A2B-v2.0?node-id=4398%3A155424
n/a
1. Go to privacy notice page and check content versus figma design
n/a
> 64069 - Privacy Notice Page content changes

- Dfe.Academies.External.Web.UnitTest/Extensions/StartupExtensionTests.cs
- Dfe.Academies.External.Web/Extensions/StartupExtensions.cs
- Dfe.Academies.External.Web/appsettings.Development.json
- Dfe.Academies.External.Web/appsettings.json
- README.md
* For us to be able to set parameters defined in `appsettings.json` as Environment Variables, the names can't contain hyphens.
* For this to work on running environments, we will need to add the new variable names in before we merge/deploy this
> Change parameters in `appsettings.json` to use underscores in stead of hyphens

- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Amending non-chair 'you can't submit' text toa GDS warning
n/a
1. TBC
2.
3.
4.
n/a
> app overview - amending no chair text to be a GDS warning

- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112258?McasTsid=26110
Everything done on ticket, bar the buttons (add school / add trust) should be left aligned
n/a
1. go to application overview page with no school or trust and add school / add trust buttons should be aligned left
2.
3.
4.
n/a
> remove text pull right css class on buttons

- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml.cs
- Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
tickets already resolved so no ticket
1. leases marked as no, without any leases - 'not started' button shows
2. loans marked as no, without any leases - 'not started' button shows
1. go to finance summary - leases marked as no - heading status = 'NotStarted'
2. go to finance summary - leases marked as yes - heading status = 'Complete'
3. go to finance summary - loans marked as no - heading status = 'NotStarted'
4. go to finance summary - loans marked as yes - heading status = 'Complete'
n/a
> amend finance summary section status to use new flags (leases & loans)

- Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
- Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
See below tickets:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112106?McasTsid=26110
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112108?McasTsid=26110
Amend banner text (after save)
Amend email substitutions - school name not being sent down the wire
1. Add a contributor (using ONLY configured email address on gov uk notify). Press save
2. When you receive email, school name DOES NOT show
1. Add a contributor (using ONLY configured email address on gov uk notify). Press save
2. Banner text should be same as ticket
3. When you receive email, school name should now show
n/a
> 112106 email contributor fixes

- Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
See below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112106?McasTsid=26110
A) It has appeared to fail as where the Design says "Success", the actual page says "Contributor added".
B) The message on the design under "Success" states "Contributor added" as a heading where as the actual page says "Abi Adebanjo has been sent an invitation to help with this application."
C) The design also has this above text underlined in a smaller font.
1. go to app overview, invite a contributor, success banner doesn't look like attached screenshot
1. go to app overview, invite a contributor, success banner doesn't look like attached screenshot
n/a
> invite a contributor banner title & content mods

- Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolChangesToATrust.cshtml
- Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolChangesToATrust.cshtml.cs
See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104661?McasTsid=26110
a) amended css class changed  to 'govuk-caption-l' same as other parts of the system
b) '?' added and css class changed to 'govuk-label' same as other parts of the system where optional textboxes are shown
scenario 8) validation text changed
1. go to application overview, 'trust details', 'change your answers', step 2, 'for example ..' - wrong font
2. go to application overview, 'trust details', 'change your answers', step 2, 'what are the changes ...' missing '?'
3. validation warning text not as per UAC
1. go to application overview, 'trust details', 'change your answers', step 2, 'for example ..' - rightfont
2. go to application overview, 'trust details', …
> 104661 minor changes to the trust fixes

- Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolChangesToATrust.cshtml
- Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolLocalGovernanceArrangements.cshtml
See comments on below ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104662?McasTsid=26110
1 A) "For example, setting up a local sub-regional hub or changes to any schemes of delegation." text should ideally be grey
B) Text under selected "Yes" option should read "What are the changes and how do they fit into the current lines of accountability in the trust?" and should be in black
C) Yes radio button option looks very close to the text above it compared to the design.  Perhaps a couple more line-breaks should be added here
1. go to application overview, trust details, change answers, step 3 of 3 page has 3 styling issues (as above)
1. go to application overview, trust details, change answers, step 3 of 3 page no longer has 3 styling …
> 104662 styling fixes

- Dfe.Academies.External.Web/Models/NewTrust.cs
n/a
If you try and go into a FAM application on application overview code blow up with following:-
Dfe.Academies.External.Web.Services.ConversionApplicationRetrievalService: Error: ConversionApplicationRetrievalService::GetApplication::Exception - Each parameter in the deserialization constructor on type 'Dfe.Academies.External.Web.Models.NewTrust' must bind to an object property or field on deserialization. 
Each parameter name must match with a property or field on the object. The match can be case-insensitive.
1. Go into a FAM application from your applications, you can't
1. Go into a FAM application from your applications, you can
n/a
> new trust serilization bug fix

- Dfe.Academies.External.Web.UnitTest/ViewModels/ConversionApplicationContributorViewModelTests.cs
- Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
- Dfe.Academies.External.Web/Pages/Shared/_ApplicationContributorsPartial.cshtml
- Dfe.Academies.External.Web/ViewModels/ConversionApplicationContributorViewModel.cs
see below ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113668?McasTsid=26110
User is able to remove themselves as a contributor which means they would kick themselves out of the application
1. go to application overview
2. click on invite contributors
3. can see 'remove contributor' link for self
1. go to application overview
2. click on invite contributors
3. can't see 'remove contributor' link for self
n/a
> remove a contributor - can remove self

- Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDateSummaryModelTests.cs
- Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustSummaryModelTests.cs
- Dfe.Academies.External.Web/Pages/Base/BaseTrustFAMApplicationSummaryPageModel.cs
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustName.cshtml.cs
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDate.cshtml.cs
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDateSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDateSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustSummary.cshtml.cs
- Dfe.Academies.External.Web/ViewModels/SummaryPages/ApplicationSchoolJoinAMatTrustSummarySectionViewModel.cs
- Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustOpeningDateHeadingViewModel.cs
- Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustOpeningDateSectionViewModel.cs
See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107013
New fam trust opening date summary page to show input fam trust opening date data
n/a
1. Page is called from FAM Trust overview page which doesn't exist yet
2. So, to preview page, go to URL directly:- https://localhost:44350/trust/form-amat/application-new-trust-opening-date-summary?appId=7
n/a
> 107103 fam trust opening date summary page

- Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultationSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/DeclarationSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml
- Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/PupilNumbersSummary.cshtml
see below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113836?McasTsid=26110
Tables on summary pages missing the following:-
1) no thead tag
2) no aria-describedby on table itself explaining contents
1. see ticket for details
1. see ticket for details
n/a
> Fix Summary Pages Sonar source accessibility issues

- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
2 bugs against:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112258?McasTsid=26110
1) add school button green not grey
2) non-chair top text is wrong
1. Go to app overview, no school, button is green
2. Go to app overview, as non-chair text is wrong
1. Go to app overview, no school, button is grey
2. Go to app overview, as non-chair text is right
n/a
> 113992 bug fix

- Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Fix the following issue:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113895?McasTsid=26110
FAM - When you go into trust details and change the trust you are joining by selecting a different one, all other trust details are wiped. they shouldn't be
1. FAM - When you go into trust details and change the trust you are joining by selecting a different one, all other trust details are wiped. they shouldn't be
1. FAM - When you go into trust details and change the trust you are joining by selecting a different one, 
2. then go into trust details summary page, details not wiped
3.
4.
n/a
> fix to handle if existing trust data already exists

- Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustReasonsModelTests.cs
- Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummaryModelTests.cs
- Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
- Dfe.Academies.External.Web/Pages/School/LeaseDetails.cshtml
- Dfe.Academies.External.Web/Pages/School/Leases.cshtml
- Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml
- Dfe.Academies.External.Web/Pages/School/Loans.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasons.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasons.cshtml.cs
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummary.cshtml.cs
see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107019
Build new page to capture FAM - Trust reasons for forming the trust (details) page
n/a
1. go into the app overview for a FAM application type
2. go into trust details / summary page
3. click 'reasons for forming a trust' link
4. click on reasons link (stub page)
5. you'll then see new page:- https://localhost:44350/trust/form-amat/application-new-trust-reasons?appId=7
n/a
> 107019 - FAM - Trust reasons for forming the trust (details) page

- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/114091?McasTsid=26110
Double application submission causes yellow screen of death. so, stop an application being submitted after it's been submitted!
1. Go to app overview as chair, with all details filled in, submit application
2. you can go back to  app overview as chair and still see submit button
1. Go to app overview as chair, with all details filled in, submit application
2. you can go back to  app overview as chair and you WON'T see submit button
n/a
> Only show submit button if application status = in progress

- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDate.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDate.cshtml.cs
See bug sub-tasks against ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/106398?McasTsid=26110
BUG: v1.5: Scenario 1: A couple of potential minor cosmetic and content issues
Scenario 13 fails.  A user is able to submit an invalid email address e.g. abc
BUG v1.5: Scenario 10 fails.  A user is able to input numerical text in the name field e.g. the floating point number outlined in the scenario.
1. to to app overview for FAM application
2. go to trust details
3. click on 'opening date'
4. click on 'change answers' / start
5. input invalid email, check other 2 issues
1. to to app overview for FAM application
2. go to trust details
3. click on 'opening date'
4. click on 'change answers' / start
5. input invalid email, check other 2 issues …
> 106398 bug fixes

- Dfe.Academies.External.Web/Pages/ApplicationSubmitted.cshtml
See last comment on:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104227?McasTsid=26110
mailto link on page not using correct CSS
1. go to application submitted page
2. mailto link not correct font / colour
1. go to application submitted page
2. mailto link correct font / colour
n/a
> add missing class to mailto

- Dfe.Academies.External.Web/Pages/WhatAreYouApplyingToDo.cshtml
See:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113381?McasTsid=26110
Text above radio buttons should be grey on What are you applying to do page
1. Text above radio buttons should be grey on What are you applying to do page
1. Text above radio buttons is grey on What are you applying to do page
n/a
> What are you applying to do? Content change

- Dfe.Academies.External.Web/Pages/Accessibility.cshtml
- Dfe.Academies.External.Web/Pages/Index.cshtml
- Dfe.Academies.External.Web/Pages/Privacy.cshtml
- Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
- Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml
- Dfe.Academies.External.Web/Pages/School/Declaration.cshtml
- Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml
- Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml
see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113841
Any link within the application which opens in a new tab / new window MUST have the following attribute rel="noopener" to avoid clickjacking
See here for 27 security hotspots:-
https://sonarcloud.io/project/security_hotspots?id=DFE-Digital_Dfe.Academies.External
n/a
1. go to any page that's been modified to ensure links on page still work
n/a
> 113841 sonar source link warnings

- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
- Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml
- Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml
- Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml.cs
Some tweaks on app overview / school overview page for FAM journey. Ahead of estimation
NO changes to JAM journey
Some tweaks on app overview / school overview page for FAM journey. Ahead of estimation
Implementing design layout on tickets:-
- 106396
- 112305
- 112306
n/a
1. go to app overview page where app type = FAM with school, you'll see a) additional status against school, b) remove school button added, c) school name link goes to school overview page and d) amended title text above schools & trust as per ticket
2. go to app overview page where app type = FAM without school. Just see add school button ONLY
3.
4.
n/a
> 113208 fam school overview page statuses mainly

- Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
See comments about trust status logic on:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112305?McasTsid=26110
coded up CalculateFormAMatTrustStatus() for FAM app overview
n/a
1. go to app overview - application type = FAM
2. trust status now shows not started / InProgress / completed
n/a
> coded up CalculateFormAMatTrustStatus() for FAM app overview

- Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolTrustConsent.cshtml
see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/114775?McasTsid=26110
navigate to FAM trust consent page and page no longer says you must attach document
1. navigate to FAM trust consent page and page says you must attach document
1. navigate to FAM trust consent page and page no longer says you must attach document
n/a
> remove inset text

- Dfe.Academies.External.Web.UnitTest/Pages/RemoveSchoolSelectionModelTests.cs
- Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
- Dfe.Academies.External.Web/Pages/RemoveSchoolSelection.cshtml
- Dfe.Academies.External.Web/Pages/RemoveSchoolSelection.cshtml.cs
- Dfe.Academies.External.Web/Pages/Shared/_ErrorMessages.cshtml
see:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113358?McasTsid=26110
Add remove a school selection screen
n/a
1. FAM - application overview - press remove school button
2. Ensure you go to new page
3. Press 'Remove school' button with no school selected, ensure get correct validation message
4. Press 'Remove school' button with school selected, ensure go to non existent page
n/a
> 113358 - Add remove a school selection screen

- Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceSummaryModelTests.cs
- Dfe.Academies.External.Web.UnitTest/Pages/Trust/JoinAMat/ApplicationSchoolJoinAMatTrustSummaryModelTests.cs
- Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultationSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/DeclarationSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml
- Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml
- Dfe.Academies.External.Web/Pages/School/PupilNumbersSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceSummary.cshtml.cs
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategySummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDateSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolJoinAMatTrustSummary.cshtml
- Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolJoinAMatTrustSummary.cshtml.cs
see ticket:-
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/116006
Axe & wave issues on following pages:-
- ApplicationPreOpeningSupportGrantSummary
- ApplicationSchoolConsultationSummary
- DeclarationSummary
- Finances summary
- FurtherInformationSummary
- LandAndBuildingsSummary
- PupilNumbersSummary
- ApplicationNewTrustGovernanceSummary
- ApplicationNewTrustImprovementStrategySummary
- ApplicationNewTrustOpeningDateSummary 
- ApplicationNewTrustReasonsSummary
- ApplicationSchoolJoinAMatTrustSummary 
Axe & wave issues on following pages:-
- ApplicationPreOpeningSupportGrantSummary
- ApplicationSchoolConsultationSummary
- DeclarationSummary
- Finances summary
- FurtherInformationSummary
- LandAndBuildingsSummary
- PupilNumbersSummary
- …
> fix axe & wave critical & errors on summary pages

- Dfe.Academies.External.Web/ViewModels/ApplicationSchoolContactsViewModel.cs
see tickets:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/114296?McasTsid=26110
Everywhere in the app where an email address is input there should be validation for a valid email address
can enter 'potato' into School main contacts - head email address
can enter 'potato' into School main contacts - chair email address
can enter 'potato' into School main contacts - other email address
can enter 'potato' into School main contacts - approver email address
can't enter 'potato' into School main contacts - head email address
can't enter 'potato' into School main contacts - chair email address
can't enter 'potato' into School main contacts - other email address
can't enter 'potato' into School main contacts - approver email address
n/a
> 114296 - add email validation where it's missing

- .github/workflows/cd-development.yml
* The set-output command is depreciated. This refactors the workflows to output them into the GITHUB_OUTPUT environment variable instead.
* Warning: The \`set-output\` command is deprecated and will be disabled soon.
> Refactor GitHub workflow outputs

- .github/workflows/build-and-push-image-test.yml
This pull request adds an image build and push workflow for the new Test environment in CIP. The image build will use the source code checked out to the GitHub tag `pre-release`.
> Add image build stage for Test/PreProd env

- Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
the SubmitApplication in the ConversionApplicationCreationService has been changes to accept/deserialise a generic "Object" response.
the API ATM is returning a list of schools
We do not use the response for anything at the moment so deserialising to an "Object" is fine
> 125932 fam application submission failure

- .github/workflows/build-and-push-image.yml
- .github/workflows/security-tests.yml
Changes any instance of using `vars` to `secrets` for Cypress tests workflows
> Update test workflows to use secrets instead of vars

- .github/workflows/security-tests.yml
- Dfe.Academies.External.Web/CypressTests/cypress.config.ts
- Dfe.Academies.External.Web/CypressTests/cypress/plugins/generateZapReport.js
- Dfe.Academies.External.Web/CypressTests/package.json
Fixes ZAP workflow not generating a report after test run.
Uses env vars rather than cypress vars to configure zap proxy
[Example run](https://github.com/DFE-Digital/Dfe.Academies.External/actions/runs/5819811892/job/15778948575)
> Fix zap script

- Dfe.Academies.External.Web/Pages/Shared/_Layout.cshtml
Resolves #513 
The app should load a page without any font assets reporting 404 status codes
1. Load Dev Tools / Inspector on a Browser
2. Make a request to the homepage
3. Note a number of 404s to Font assets
1. Load Dev Tools / Inspector on a Browser
2. Make a request to the homepage
3. Confirm all the CSS assets are loading as expected 
4. Confirm there has been no visual regression
5. Confirm that there are no 404s to Font assets 
N/A
> Removed duplicate stylesheet reference

- Dfe.Academies.External.Web/CypressTests/cypress.config.ts
Adds a User-Agent header to Cypress' config to mitigate Azure's bot traffic rules
> Add Cypress User-agent to config

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Whilst the Origin is pointing to an App Gateway, Health Probes are failing. They aren't strictly necessary when we only have 1 origin so we can turn them off. Source: https://learn.microsoft.com/en-us/azure/frontdoor/health-probes\#disabling-health-probes
> Disable CDN origin health probe

- .github/workflows/build-and-push-image.yml
* Once the image has been built and pushed to GHCR, the `acr-import` job will then trigger an `acr import` to the given environment `ACR_NAME`
* All tags will be imported (via the for loop, using the 3 tagged images)
* Currently this is restricted to just the 'development' environment for testing purposes.
> Add ACR Import to buid-and-psuh workflow

- .github/workflows/build-and-push-image.yml
* The `az containerapp update` for development can now pull from the new ACR (Which has had an image imported from GHCR).
> Pull image from new ACR in the workflow

- .github/workflows/build-and-push-image.yml
* We are using import to update 'latest' and 'master' (for the branch name) tags. If the tag exists, we get the error:
> tag already exists in target registry
Setting `--force` will overwrite the tag
> Force acr import in workflow

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Bumps the container-app-hosting module to v1.6.1 which allows changing the registry server without removing the default ACR
* Adds the `registry_server` variable, used in the module
> Add variables to allow changing registry

- .github/workflows/dotnet.yml
Sets paths to restrict when to run build and test.
This is to reduce the amount of times that sonarcloud is ran and to free up github runners
> Add exclusion paths for build and test

- Dfe.Academies.External.Web/Pages/Shared/_Layout.cshtml
- Dfe.Academies.External.Web/Pages/Shared/_NotificationBanner.cshtml
- Dfe.Academies.External.Web/appsettings.json
* By setting the value of 'NotificationBannerMessage' to a non-empty string, the govuk notification banner will be displayed above the header. This can be used for informing users of upcoming service changes or other important messages
> Toggleable Notification Banner

- Dfe.Academies.External.Web/Pages/Shared/_NotificationBanner.cshtml
There is an invalid css class applied so this PR corrects it to the govuk container
> Set class to govuk to match existing branding

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
This change allows us to override the default SKU selected for Redis Cache.
In Production we should change this from the default 'Basic' to 'Standard' so that we can leverage the 99.9% availability SLA
> Set SKU tier for Redis

- Dockerfile
Tracking the 8.0.x tag allows us to capture upstream security updates from Microsoft
> CVE-2024-21392

- Dfe.Academies.External.Web/Program.cs
This PR simply adds the configuration overrides for the `useHsts()` method.
This allows us to set the `max-age` parameter to 365 days, and turn on `preload`
> Configure HSTS settings for ASP.NET

- Dfe.Academies.External.Web/Program.cs
- Dfe.Academies.External.Web/Security/SecureHeadersDefinitions.cs
- Set Xss Protection to 0
- Set HSTS in all environments
- Ensure X-Forwarded headers are passed to dotnet
> Ensure HSTS is set for requests behind a proxy

- Dfe.Academies.External.Web/Pages/Cookies.cshtml
- Dfe.Academies.External.Web/Pages/Shared/_Layout.cshtml
- Dfe.Academies.External.Web/Security/SecureHeadersDefinitions.cs
User telemetry is now available in App Insights if the user opts into Analytical Cookies.
This data will include browser-based metrics such as page speed and Time-til First Byte (TTFB). I have set the AuthenticatedUserContext which means we can track individual user sessions throughout their journey. In addition, I have also included the click tracking plugin which enables us to have almost feature parity with Google Analytics and Google Tag Manager.
1. Accept Analytical Cookies
2. Sign-in using DFE Sign-in
3. View front-end telemetry in App Insights
> Application Insights front-end telemetry

- Dockerfile
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Reduces the overall final image size by using Azure Linux
* Offers maximum compatibility with Azure infrastructure
* Uses arbitrary user instead of 'root'
* Supported by Microsoft
https://github.com/dotnet/dotnet-docker/blob/main/documentation/azurelinux.md#azure-linux
>[!WARNING]
>Note: ASP.NET Core apps (in official images) listen to [port 8080 by default⁠](https://github.com/dotnet/dotnet-docker/blob/6da64f31944bb16ecde5495b6a53fc170fbe100d/src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile#L7), starting with .NET 8. This is because it is using an arbitrary user. As a result we will need to update the Container App definition to list to Port 8080
> Switch to Azure Linux base image

- Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewFAMApp.cy.ts
- Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewJAMApp.cy.ts
- Dfe.Academies.External.Web/CypressTests/cypress/support/commands.ts
Re-enable accessibility checks and enable retries for aXe and A11y when elements are being redrawn initially throwing an accessibility violation in error
> Auto re enable all accessibility checks

- .github/workflows/cypress-tests.yml
- Dfe.Academies.External.Web/CypressTests/cypress.config.ts
- Dfe.Academies.External.Web/CypressTests/cypress/cypress.config.js
**Summary:**
This PR enhances the Cypress test configuration by integrating Slack notifications to provide real-time updates on test results. Additionally, it ensures the reporting functionality is consistent and well-structured.
---
**Changes:**
1. **Added Slack Notifications:**
- Integrated Slack notifications using a webhook.
- Configured the `after:run` event to send a summary of Cypress test results to a specified Slack channel.
- Notifications include total tests, passed tests, and failed tests with dynamic color-coded messaging.
- Other information has been added. 
2. **Updated Cypress Reporter Configuration:**
- Fixed a typo in the `mochawesomeReporterOptions` (`quite` → `quiet`).
- Verified reporting outputs JSON files to `cypress/reports/mocha`.
3. **Improved CI Feedback Loop:** …
> Add Slack Notifications to Cypress Test Results

- .gitignore
- Dfe.Academies.External.Web/CypressTests/package-lock.json
- Dfe.Academies.External.Web/CypressTests/package.json
This PR updates the `package.json` file in the `Dfe.Academies.External.Web/CypressTests` folder, making adjustments to the dependencies and scripts for improved functionality and consistency.
1. **Scripts Updates:**
- Consolidated and streamlined the `generate:html:report` script to combine and generate reports in a single command.
- Removed duplicate entries for `lint` and `generate:html:report` scripts.
2. **Dependencies Adjustments:**
- Added `typescript` with version `^5.1.6` to the `dependencies` section.
- Removed duplicate entries for `cypress-multi-reporters` and `zaproxy` in the `devDependencies` section.
- Ensures a cleaner `package.json` file with no duplicate or redundant entries.
- Improves maintainability by aligning dependencies and scripts.
- Enhances clarity for future …
> Cypress slack notifications with other changes

- Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewFAMApp.cy.ts
- Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewJAMApp.cy.ts
- Dfe.Academies.External.Web/CypressTests/cypress/e2e/deleteNewJAMApp.cy.ts
- Dfe.Academies.External.Web/CypressTests/cypress/e2e/inviteAndRemoveContributor.cy.ts
- Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/application.ts
- Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/home.ts
- Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/preOpeningSupportGrantDetails.ts
- Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/preOpeningSupportGrantSummary.ts
Added negative tests for all spec files to check homepage banners no longer display post-midnight of the day of Friday 20th December 2024
Added negative tests to JAM and FAM journey spec files to check banners removed from Application overview page and that the Conversion support grant link no longer displays for new users (JAM/FAM journeys)
> Test check conversion support grant banners no longer exist

- .github/workflows/docker-test.yml
- .github/workflows/dotnet.yml
- Dfe.Academies.External.Web/Program.cs
* Adds a new route /health which is where .NET will report on the status of the application. We can use this for HTTP Monitors
> Register health route for app

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* The default health check route is `/` but now that we have `/health` available in the Dev environment we might want to override these values.
> Enable overriding of health check routes used by infrastructure monitors

- .github/workflows/dotnet.yml
This forms part of the work to make Sonarqube a mandatory quality gate.
Introducing the `sonar.qualitygate.wait=true` parameter ensures that the scanner will wait for the report to be generated and will fail the workflow if the gate is red, rather than completing the workflow regardless of the gate
> Wait for quality gate response from Sonar before finishing the workflow

- .github/workflows/build-and-push-image.yml
Publish artifact attestation along with the container image digest to GitHub Container Registry.
This metadata bundle helps to validate the providence of the source code used to build the container image.
Read: https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
> Update Deploy Container action to 5.2.0
