DFE-Digital/Dfe.Academies.External

specification/ApplyToBecomeAnAcademy/01 Start Feature/03 Your Applications List Page.md

refer to page name rather than page title
minor gherkin style & formatting changes

95253 your applications list page

---

Dfe.Academies.External.Web.UnitTest/Dfe.Academies.External.Web.UnitTest.csproj
Dfe.Academies.External.Web.UnitTest/Routing/HyphenateRouteParameterTransformerTest.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Routing/HyphenateRouteParameterTransformer.cs
Dfe.Academies.External.sln

Adding a Parameter Transformer to convert hyphenated URLs to Pascal Case filenames

AB#98184 Lowercase Hyphenated URLs - add Parameter Transformer class

---

Dfe.Academies.External.Web/Pages/Index.cshtml
specification/ApplyToBecomeAnAcademy/01 Start Feature/01 Landing Page.md

AB#95250 Landing Page - add figma link to spec

---

Dfe.Academies.External.Web.UnitTest/Pages/WhatAreYouApplyingToDoModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/ValidationErrorMessagesViewModelTests.cs
Dfe.Academies.External.Web/Pages/Base/BasePageModel.cs
Dfe.Academies.External.Web/Pages/Shared/_ErrorMessages.cshtml
Dfe.Academies.External.Web/Pages/Shared/_ValidationSummary.cshtml
Dfe.Academies.External.Web/Pages/WhatAreYouApplyingToDo.cshtml
Dfe.Academies.External.Web/Pages/WhatAreYouApplyingToDo.cshtml.cs
Dfe.Academies.External.Web/Pages/WhatYouWillNeed.cshtml.cs
Dfe.Academies.External.Web/Pages/YourApplications.cshtml.cs
Dfe.Academies.External.Web/ViewModels/ValidationErrorMessagesViewModel.cs

Changes in Dfe.Academies.External.Web && Dfe.Academies.External.Web.UnitTest
Dfe.Academies.External.Web Changes are:-
1) Created BasePageModel
2) Implement BasePageModel on YourApplications.cshtml and WhatAreYouApplyingToDo.cshtml
3) Amended _ValidationSummary to consume a full on viewModel
4) Created ValidationErrorMessagesViewModel
5) Amended BasePageModel to have ValidationErrorMessagesViewModel
6) Amended pages that consume BasePageModel to implement new helper method
Dfe.Academies.External.Web.UnitTest Changes are:-
1) Added tests for ValidationErrorMessagesViewModel
2) Amended tests consuming error model to be in line with new object format

implemented BasePageModel for modelstate -> dictionary conversion

---

Dfe.Academies.External.Web/Models/ConversionApplication.cs
Dfe.Academies.External.Web/Pages/YourApplications.cshtml
Dfe.Academies.External.Web/Pages/YourApplications.cshtml.cs

Just a quick simple code change to avoid null checks

YourApplicationsMinorMod

---

Dfe.Academies.External.Web/Pages/Shared/_CookieConsentPartial.cshtml

To fix an incorrect font on the cookie warning banner

add missing class

---

Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
Dfe.Academies.External.Web/Pages/_ViewImports.cshtml
Dfe.Academies.External.Web/TagHelpers/StatusTagHelper.cs

Added a custom TagHelper to render styles for a status box (strong HTML element) similar to the below:-
https://govuk-prototype-kit.herokuapp.com/docs/templates/task-list

Implement custom TagHelper to show the application status / component status

---

Dfe.Academies.External.Web/appsettings.Development.json
Dfe.Academies.External.Web/appsettings.json

Bug Fix
c# converts endpoint setting value to a URI. So needs to be a valid URI in settings

c# converts endpoint to a URI. So needs to be a valid URI

---

Dfe.Academies.External.Web/Pages/WhatAreYouApplyingToDo.cshtml

This is to tackle story 100446 - remove back button.
And, a sub task against story 97100 - move position of left hand bar on validation error to be in line with figma
Still outstanding is something to do with validation warnings margins

100446 what are you applying to do styling mods

---

Dfe.Academies.External.Web/Pages/Index.cshtml

- minor text modifications and making links open in new window

Amend landing page content & link functionality

---

Dfe.Academies.External.Web/Pages/Index.cshtml
Dfe.Academies.External.Web/Pages/WhatIsYourRole.cshtml
Dfe.Academies.External.Web/Pages/YourApplications.cshtml

1) Add class="govuk-link" to anchor tags on home / landing page
2) fixed capitalised 'Is'
3) Add class="govuk-link" to anchor tags on your applications page

HTML fix ups

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml

app overview fix for JoinMat route - Amendment to how a nullable status is handled on the page as this was causing an app crash

app overview fix for JoinMat route

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs

1) Amended add school / add trust button to use secondary button style
2) Added trust status back in for join a mat

Small Application overview styling changes

---

Dfe.Academies.External.Web.UnitTest/Pages/CookiesModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/ErrorModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/IndexModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/PrivacyModelTests.cs

Just more Code coverage unit tests pages

Code coverage unit tests pages

---

Dfe.Academies.External.Web.UnitTest/Models/SchoolSearchTests.cs
Dfe.Academies.External.Web.UnitTest/Models/SchoolsSearchDtoTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ReferenceDataRetrievalServiceTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/SchoolSearchResultViewModelTests.cs
Dfe.Academies.External.Web/Extensions/StartupExtensions.cs
Dfe.Academies.External.Web/Models/SchoolSearch.cs
Dfe.Academies.External.Web/Models/SchoolsSearchDto.cs
Dfe.Academies.External.Web/Services/IReferenceDataRetrievalService.cs
Dfe.Academies.External.Web/Services/ReferenceDataRetrievalService.cs
Dfe.Academies.External.Web/ViewModels/SchoolSearchResultViewModel.cs

1) Create SchoolDetailsViewModel - for rendering school details
2) Create SchoolSearchResultViewModel - Frontend model class used only for UI rendering
3) Created ReferenceDataRetrievalService && IReferenceDataRetrievalService to access schools search API endpoint
4) Added unit tests for new view models
5) Added ReferenceDataRetrievalServiceTests
6) Amended StartupExtension - Extra DI for ReferenceDataRetrievalService
7) Added school search filter && school result dto to mimic whatever the academies API expects to be input & returns

Data retrieval service / models / tests

---

Dfe.Academies.External.Web.UnitTest/Models/SchoolApplyingToConvertTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceTests.cs
Dfe.Academies.External.Web/Models/ApiPostResult.cs
Dfe.Academies.External.Web/Models/ConversionApplicationApiPostResult.cs
Dfe.Academies.External.Web/Models/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs

1) Amended ConversionApplicationCreationService to have AddSchool method - to wire up to endpoint
2) Amended ConversionApplicationCreationServiceTests - new test for new method

Add AddSchoolToApplication method & test

---

Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs

2 minor mods to remove some code warnings

Code warning fixes pt1

---

Dfe.Academies.External.Web.UnitTest/AcademiesAPIResponseModels/EstablishmentResponseTests.cs
Dfe.Academies.External.Web.UnitTest/Controllers/SchoolControllerTests.cs
Dfe.Academies.External.Web.UnitTest/Controllers/TrustControllerTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/Trust/ApplicationSelectTrustModelTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/Trusts/TrustSearchDto.cs
Dfe.Academies.External.Web/Controllers/BaseController.cs
Dfe.Academies.External.Web/Controllers/SchoolController.cs
Dfe.Academies.External.Web/Controllers/TrustController.cs
Dfe.Academies.External.Web/Pages/Shared/_TrustDetails.cshtml
Dfe.Academies.External.Web/Pages/Trust/ApplicationSelectTrust.cshtml
Dfe.Academies.External.Web/Pages/Trust/ApplicationSelectTrust.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs
Dfe.Academies.External.Web/ViewModels/SchoolSearchResultViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustDetailsViewModel.cs
Dfe.Academies.External.Web/wwwroot/js/academies.trustsearch.js

Implement trust search UI:-
1) New ApplicationSelectTrust page
2) New _TrustDetails partial view to display selected trust
3) academies.trustsearch.js - to do heavy lifting between UI & backend
4) TrustController - to wire up to trams API
5) New ApplicationSelectTrust page unit tests
To review HTML use following test URL:-
https://localhost:44350/trust/application-select-trust?appId=0

Trust search UI only

---

Dfe.Academies.External.Web.UnitTest/AcademiesAPIResponseModels/EstablishmentResponseTests.cs
Dfe.Academies.External.Web.UnitTest/Controllers/SchoolControllerTests.cs
Dfe.Academies.External.Web.UnitTest/Controllers/TrustControllerTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationJoinTrustReasonsModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/Trust/ApplicationSelectTrustModelTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/Trusts/TrustSearchDto.cs
Dfe.Academies.External.Web/Controllers/BaseController.cs
Dfe.Academies.External.Web/Controllers/SchoolController.cs
Dfe.Academies.External.Web/Controllers/TrustController.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_TrustDetails.cshtml
Dfe.Academies.External.Web/Pages/Trust/ApplicationSelectTrust.cshtml
Dfe.Academies.External.Web/Pages/Trust/ApplicationSelectTrust.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs
Dfe.Academies.External.Web/ViewModels/SchoolSearchResultViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustDetailsViewModel.cs
Dfe.Academies.External.Web/wwwroot/js/academies.trustsearch.js

Create reasons for joining trust Page same as 'as-is' and as per below ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/102483?McasTsid=26110
To review HTML use following test URL:-
https://localhost:44350/school/application-join-trust-reasons?appId=2147483647&applyingSchoolId=96

102483 reasons for joining

---

Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationChangeSchoolNameModelTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs

Create change the name of the school Page same as 'as-is' and as per below ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/102520?McasTsid=26110
To review HTML use following test URL:-
https://localhost:44350/school/application-change-school-name?appId=2147483647&applyingSchoolId=96

102520 - application-change-school-name page UI only

---

Dfe.Academies.External.Web.UnitTest/Controllers/TrustControllerTests.cs

wire up mock IHttpClientFactory into trust controller tests so tests are more thorough

Amend TrustController tests

---

Dfe.Academies.External.Web/AcademiesAPIResponseModels/AddressResponse.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/Base/PageSearch.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/Schools/EstablishmentResponse.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/TrustSearch.cs
Dfe.Academies.External.Web/Attributes/RequiredEnumAttribute.cs
Dfe.Academies.External.Web/Controllers/BaseController.cs
Dfe.Academies.External.Web/Controllers/SchoolController.cs
Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
Dfe.Academies.External.Web/Extensions/EnumHelper.cs
Dfe.Academies.External.Web/Pages/Base/BasePageModel.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/TagHelpers/StatusTagHelper.cs

fixes for spaces & tabs as requested on other PR. Part 1, limited to 12 files

fixes for spaces & tabs - Part 1 - 12 files ONLY!

---

Dfe.Academies.External.Web/AcademiesAPIResponseModels/AddressResponse.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/Base/PageSearch.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/Schools/EstablishmentResponse.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/TrustSearch.cs
Dfe.Academies.External.Web/Attributes/RequiredEnumAttribute.cs
Dfe.Academies.External.Web/Controllers/BaseController.cs
Dfe.Academies.External.Web/Controllers/SchoolController.cs
Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
Dfe.Academies.External.Web/Extensions/EnumHelper.cs
Dfe.Academies.External.Web/Pages/Base/BasePageModel.cs
Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_SchoolComponentsStatusPartial.cshtml
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/TagHelpers/StatusTagHelper.cs

changing route on save from schoolOverview -> ApplicationChangeSchoolName as per ticket & clarification from @Bhavik93
To review HTML use following test URL:-
https://localhost:44350/school/application-join-trust-reasons?appId=2147483647&applyingSchoolId=96

102483 change save route

---

Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml

remove temporary A2C sip code from page

remove temporary A2C sip code from page

---

Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs

Add null handling to LoadAndSetSchoolDetails after unit test exception

Add null handling to LoadAndSetSchoolDetails after unit test exception

---

Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml

1) fixing back links at the top of the page to pass the routing params
2) fixing 2 save button next step / page issues

Fixing back links & 2 save button next step/page issues

---

Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PupilNumbers.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml.cs

fix URN binding issues

---

Dfe.Academies.External.Web.UnitTest/Models/ConversionApplicationAuditEntryTests.cs
Dfe.Academies.External.Web.UnitTest/Models/ConversionApplicationComponentTests.cs
Dfe.Academies.External.Web.UnitTest/Models/ConversionApplicationContributorTests.cs
Dfe.Academies.External.Web.UnitTest/Models/ConversionApplicationTests.cs
Dfe.Academies.External.Web.UnitTest/Models/ExistingTrustTests.cs
Dfe.Academies.External.Web.UnitTest/Models/NewTrustKeyPersonTests.cs
Dfe.Academies.External.Web.UnitTest/Models/NewTrustTests.cs
Dfe.Academies.External.Web.UnitTest/Models/PersonTests.cs
Dfe.Academies.External.Web.UnitTest/Models/SchoolApplyingToConvertTests.cs
Dfe.Academies.External.Web.UnitTest/Models/SchoolContactTests.cs
Dfe.Academies.External.Web.UnitTest/Models/SchoolFinancesTests.cs
Dfe.Academies.External.Web.UnitTest/Models/SchoolLeaseTests.cs
Dfe.Academies.External.Web.UnitTest/Models/SchoolLoanTests.cs
Dfe.Academies.External.Web.UnitTest/Models/SchoolReligiousEducationTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/ApplicationAuditViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/ApplicationCacheValuesViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/ApplicationComponentViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/ConversionApplicationContributorViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/SchoolCacheValuesViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/SchoolDetailsViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/SchoolSearchResultViewModelTests.cs

Just renaming all the page test method names so they are the same / adhere to coding standards

rename test method names so inline with coding standards

---

Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs

Change ChangeSchoolNameReason -> ChangeSchoolName

change field / property to be proposed school name

---

Dfe.Academies.External.Web.UnitTest/Pages/School/PupilNumbersSummaryModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/SchoolConversionComponentHeadingViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/SchoolPupilNumbersSummaryHeadingViewModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/SchoolPupilNumbersSummarySectionViewModelTests.cs
Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/School/PupilNumbers.cshtml
Dfe.Academies.External.Web/Pages/School/PupilNumbers.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PupilNumbersSummary.cshtml
Dfe.Academies.External.Web/Pages/School/PupilNumbersSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_SchoolConversionComponentPartial.cshtml
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/ViewModels/QuestionAndAnswerConstants.cs
Dfe.Academies.External.Web/ViewModels/SchoolConversionComponentHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/SchoolConversionComponentSectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/SchoolPupilNumbersSummaryHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/SchoolPupilNumbersSummarySectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/SchoolQuestionAndAnswerSectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/SchoolQuestionAndAnswerViewModel.cs
Dfe.Academies.External.Web/appsettings.Development.json
Dfe.Academies.External.Web/appsettings.Staging.json
Dfe.Academies.External.Web/appsettings.json

1) Added Sentry nuGet package
2) Added Serilog nuGet package
3) Added Sentry.Serilog package
4) Added builder.Host.UseSerilog to Program.cs && some other program.cs config
5) Added sentry config to appsettings.json

Add sentry logging config

---

Dfe.Academies.External.Web/Pages/Error.cshtml
Dfe.Academies.External.Web/Pages/Error.cshtml.cs
Dfe.Academies.External.Web/Pages/NotFound.cshtml
Dfe.Academies.External.Web/Program.cs

When a 404 error was encountered it wasn't handled. It is now
1. Browse to a non existent route / page and get 404 browser error
1. Browse to a non existent route / page and get custom 404 error page
n/a

fixed error & 404 page routes & content

---

Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationPreOpeningSupportGrantSummaryTests.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/ViewModels/ApplicationPreOpeningSupportGrantHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/ApplicationPreOpeningSupportGrantSectionViewModel.cs

Create page as per ticket below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/103394?McasTsid=26110
New 'Pre-opening support grant' page which hangs off application overview page
n/a
1. Run Unit Tests
2. Run Dev test URL:- 
https://localhost:44350/school/application-pre-opening-support-grant-summary?appId=1&urn=101934
n/a

103394 pre opening support grant summary UI only

---

Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceTests.cs
Dfe.Academies.External.Web/Pages/YourApplications.cshtml
Dfe.Academies.External.Web/Pages/YourApplications.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationRetrievalService.cs

[Resolves #<105093>](https://dev.azure.com.mcas.ms/dfe-gov-uk/Academies-and-Free-Schools-SIP/_backlogs/backlog/Apply%20to%20become/Stories/?workitem=105093)
Wire up the list all applications endpoint and use the data on the Your Applications page.
1.
2.
3.
4.
1.
2.
3.
4.

105093 Wire up list all applications endpoint

---

Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/Models/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml
Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml.cs
Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/ResilientRequestProvider.cs

Wires up the Land a buildings summary and edit page to the academisation api PUT and GET endpoints
In this PR:
- Added Id to the schools model as this is used in the academisaton api to update the correct school data (including the land and buildings data).
- Update the LoadAndSetSchoolData Base method to get school data from the academisation api.
- Updated the school and building PopulateUIModel to set the data retrieved from the academisation api.
- Update the OnPost page method to use the createService to update the land a building data for the current school.
1.
2.
3.
4.
1.
2.
3.
4.

Wire up land and building pages to academisation api

---

Dfe.Academies.External.Web/Controllers/SchoolController.cs
Dfe.Academies.External.Web/Controllers/TrustController.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrant.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultationSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PupilNumbers.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PupilNumbersSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml.cs
Dfe.Academies.External.Web/Program.cs

Removed TODO's from code
Removed un-needed / duplicate section from application overview page
n/a
1. Ensure application overview renders correctly
2.
3.
4.
n/a

Code tidy up remove todos and tidy app overview

---

Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/Pages/School/PupilNumbers.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PupilNumbersSummary.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs

Resolves [#<104128>](https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104128)
- Wires up future pupil pages and service to use the academisation api.
- Adds service tests for future pupil number creation and update method.
1.
2.
3.
4.
1.
2.
3.
4.

104128 wire up fututre pupil numbers

---

Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
Dfe.Academies.External.Web/Extensions/BoolEnumExtension.cs
Dfe.Academies.External.Web/Models/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs

Add new API property to UI as per ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105780?McasTsid=26110
n/a
1. Run Unit tests - done as part of CI/CD
2. Go into an application without a conversion date selected - ensure 'about the conversion' & 'conversion target date' page works
3. Go into an application with a conversion date selected - ensure 'about the conversion' & 'conversion target date' page works
4. Go into an application and submit 'conversion target date' data to ensure this gets stored in the API & database
n/a

105780 conversion target date specified addition

---

Dfe.Academies.External.Web/Pages/Shared/_Footer.cshtml

Resolves [#<105750>](https://dev.azure.com.mcas.ms/dfe-gov-uk/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=105750)
- Fixes Footer links to work from school pages
1.
2.
3.
4.
1.
2.
3.
4.

Fix link paths for footer so it works from School pages

---

Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/Models/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs

Wire up change school name API properties:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104125?McasTsid=26110
n/a
1. Run Unit tests - done as part of CI/CD
2. Go into an application without a conversion date selected - ensure 'about the conversion' & 'conversion target date' page works
3. Go into an application with a conversion date selected - ensure 'about the conversion' & 'conversion target date' page works
4. Go into an application and submit 'conversion target date' data to ensure this gets stored in the API & database
n/a

105859 wire up change school name page upto api

---

Dfe.Academies.External.Web/Controllers/CookiesController.cs
Dfe.Academies.External.Web/Pages/Shared/_CookieConsentPartial.cshtml
Dfe.Academies.External.Web/Program.cs

Resolves [#<105709>](https://dev.azure.com.mcas.ms/dfe-gov-uk/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=105709)
- Fixes Cookie Banner
1.
2.
3.
4.
1.
2.
3.
4.

Cookie banner

---

Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web/Extensions/EnumHelper.cs
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/ViewModels/SchoolConversionComponentSectionViewModel.cs

Resolves [#<104129>](https://dev.azure.com.mcas.ms/dfe-gov-uk/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=104129)
Wires up the school contact details edit and summary pages to the acadisation api.
1.
2.
3.
4.
1.
2.
3.
4.

104129 wire up school contacts page

---

Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs

Just porting another enum from SIP
n/a
n/a
n/a

porting another enum from a2c-sip

---

Dfe.Academies.External.Web.UnitTest/Pages/School/FinancialInvestigationsModelTests.cs
Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml.cs
Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml
Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml.cs
Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml.cs
Dfe.Academies.External.Web/ViewModels/FinancesReviewSectionViewModel.cs

https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/103592?McasTsid=26110
1) new financial investigations page available from finance summary
2) new financial investigations page
n/a
1. run Unit tests - done automatically by CI/CD
2. Ensure you can navigate to new financial investigations page from finance summary
3. Ensure the conditional radios work on financial investigations page and that the layout is as specified in the ticket
n/a

103592 financial investigations page

---

Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationChangeSchoolNameModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationConversionTargetDateModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationJoinTrustReasonsModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationPreOpeningSupportGrantModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationSchoolConsultationModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationSelectSchoolModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/DeclarationModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/DeclarationSummaryModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/FinancesReviewModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/LandAndBuildingsModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/NextFinancialYearModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/PreviousFinancialYearModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/PupilNumbersModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/SchoolConversionKeyDetailsModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/SchoolMainContactsModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/School/SchoolOverviewTests.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/School/Declaration.cshtml
Dfe.Academies.External.Web/Pages/School/Declaration.cshtml.cs
Dfe.Academies.External.Web/Pages/School/DeclarationSummary.cshtml
Dfe.Academies.External.Web/Pages/School/DeclarationSummary.cshtml.cs
Dfe.Academies.External.Web/ViewModels/DeclarationSummaryHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/DeclarationSummarySectionViewModel.cs

Build declaration page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104226?McasTsid=26110
And Declaration summary page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104225?McasTsid=26110
n/a
1. Run unit tests to ensure they still work, including new one's. Done by CI / CD
2. Go into an application, click on declaration. Ensure Declaration summary page displays correctly as per ticket
3. Click on 'Start section' ensure declaration page displays correctly as per ticket
n/a

104226 application declaration page

---

Dfe.Academies.External.Web.UnitTest/ViewModels/ConversionApplicationContributorViewModelTests.cs
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/ViewModels/ConversionApplicationContributorViewModel.cs

no ticket - teams / slack feedback minor mods
Minor mods to contributor page
Minor mod to application overview page
n/a
1. Minor mods to contributor page
2. Minor mod to application overview page
n/a

Contributor minor mods

---

Dfe.Academies.External.Web.UnitTest/Models/SchoolLoanTests.cs
Dfe.Academies.External.Web/Models/SchoolLoan.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml.cs
Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml
Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Loans.cshtml
Dfe.Academies.External.Web/Pages/School/Loans.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Services/TempDataHelper.cs
Dfe.Academies.External.Web/ViewModels/FinancesReviewSectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/LoanViewModel.cs

Resolves:-
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/103590/
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/103858/
You can progress the loan section under finances and the loans will be sent to the API
Added loan functionality to the school finances section
1. Go to the finance review page
2. Fill out the loans section
3. Confirm the data is saved in the database
n/a

103590 loans

---

Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml
Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Loans.cshtml

To fix following Bugs:-
Loan Details page - Incorrect button text
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108495?McasTsid=26110
Loan Details page - incorrect label styles
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108491?McasTsid=26110
Loans Page - Not showing currency symbol
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108774?McasTsid=26110
1. Loan Details page - has correct button text
2. Loan Details page -  has correct label styles
3. Loans Page - has currency symbol
1. Loan Details page - Incorrect button text
2. Loan Details page - incorrect label styles
3. Loans Page - Not showing currency symbol
1. Loan Details page - has correct button …

Loans details bugs various

---

Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml.cs

Contact Details page - text incorrect
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108976?McasTsid=26110
Contact Details page - other contact - email input box - not set as type=email
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108985?McasTsid=26110
Contact Details page - other contact - telephone number input box - not set as type=number
Add a contributor page - name input had type = email
1. Contact Details page - text incorrect - after radio. said schools
2. Contact Details page - other contact - email input box - not set as type=email
3. Add a contributor page - name input had type = email
4. Contact Details page - other contact - telephone number input box - not set as type=number
1. Contact …

Miscellaneous bugs

---

Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml.cs
Dfe.Academies.External.Web/ViewModels/ApplicationSchoolContactsViewModel.cs

Fix following bug, which isn't a bug but a list of minor mods / UI polishing:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108413?McasTsid=26110
Also, amended invalid email address validation messages to be correct!
When application already has a chair contributor page is showing radio and doesn't need to
1. When application already has a chair contributor page is showing radio and doesn't need to
1. When application already has a chair contributor page is NOT showing radio and couple of other styling mods
n/a

108413 invite a contributor mods

---

Dfe.Academies.External.Web/Pages/School/LeaseDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Leases.cshtml
Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Loans.cshtml
Dfe.Academies.External.Web/Services/TempDataHelper.cs

Resolves [#108779](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=108779)
The loan details aren't saving when editing an existing loan
1.
2.
3.
4.
1.
2.
3.
4.

Bugfix for loans and leases not saving details

---

Dfe.Academies.External.Web.UnitTest/Models/SchoolLeaseTests.cs
Dfe.Academies.External.Web/Models/CreateLeaseCommand.cs
Dfe.Academies.External.Web/Models/SchoolLease.cs
Dfe.Academies.External.Web/Models/UpdateLeaseCommand.cs
Dfe.Academies.External.Web/Pages/School/LeaseDetails.cshtml.cs
Dfe.Academies.External.Web/ViewModels/LeaseViewModel.cs

Resolves [110186](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=110186)
Lease term should support text
1. Fill out the lease details
2. Check if the lease term can contain free text
3.
4.
1.
2.
3.
4.

Updated lease term to be a string

---

Dfe.Academies.External.Web/Pages/School/Leases.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Loans.cshtml.cs

Loan page should redirect to the lease page when saving, and the lease page should redirect to the financial investigations page
1.
2.
3.
4.
1.
2.
3.
4.

Updated redirect paths for loans and leases pages

---

Dfe.Academies.External.Web/Pages/ApplicationAccessException.cshtml

fix bug:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/110535?McasTsid=26110
1. Back link on access exception page doesn't work
1. Back link on access exception page does work
n/a

make back link work

---

Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceTests.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
Dfe.Academies.External.Web/Pages/Base/BasePageModel.cs
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs

See ticket below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/102203?McasTsid=26110
Amendments to application overview so:-
1) section statuses not hard coded
2) submit / cancel button security is implemented
3) styling changes as per figma:-
https://www.figma.com/file/xqCVptyOcxauUXNum87EBG/A2B-v2.0?node-id=3323%3A118220
n/a
1. Review application overview layout vs figma
2. Ensure statuses shown match data against application
n/a

102203 application overview functionality

---

Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Extensions/StartupExtensions.cs
Dfe.Academies.External.Web/Models/Notifications/MessageDto.cs
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
Dfe.Academies.External.Web/Services/ContributorEmailSenderService.cs
Dfe.Academies.External.Web/Services/EmailNotificationService.cs
Dfe.Academies.External.Web/Services/IContributorEmailSenderService.cs
Dfe.Academies.External.Web/Services/IEmailNotificationService.cs
Dfe.Academies.External.Web/appsettings.json
README.md

See below ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/110868?McasTsid=26110
Contributor receives an email
n/a
1. Invite a contributor to an application, ensure that person gets an email. I think gov uk endpoint is in test mode so will only send to following people:-
- abi
- bhav
- david
- me
- paul
n/a

110868 gov uk email sending

---

Dfe.Academies.External.Web/Pages/School/ApplicationSelectSchool.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs

See bug below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107147?McasTsid=26110
When going into select school page against an application that already has a school and changing the school and pressing save exception page is shown
1. When going into select school page against an application that already has a school and changing the school and pressing save exception page is shown
1.
2.
3.
4.
n/a

107147 amending school against existing application exception

---

Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationSelectSchoolModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/Trust/ApplicationSelectTrustModelTests.cs
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
Dfe.Academies.External.Web/Pages/ApplicationAccessException.cshtml.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
Dfe.Academies.External.Web/Pages/Base/BaseApplicationPageEditModel.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/Base/BasePageModel.cs
Dfe.Academies.External.Web/Pages/Base/BaseSchoolPageEditModel.cs
Dfe.Academies.External.Web/Pages/Base/BaseSchoolSummaryPageModel.cs
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrant.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationSelectSchool.cshtml.cs
Dfe.Academies.External.Web/Pages/School/LeaseDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Leases.cshtml.cs
Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Loans.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/ApplicationSelectTrust.cshtml.cs

see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108723?McasTsid=26110
When trying to access an application you don't have access to, by changing the appId within the browser url you receive 'ApplicationAccessException' page 
n/a
Access the following pages for an application you don't have access to:-
Core pages :-
App overview
https://localhost:44350/application-overview?appId=5
AddAContributor 
https://localhost:44350/add-acontributor?appId=5
School Pages:-
ApplicationSelectSchool
https://localhost:44350/school/application-select-school?appId=5
PupilNumbersSummary
https://localhost:44350/school/pupil-numbers-summary?appId=5&urn=123332
PupilNumbers
https://localhost:44350/school/pupil-numbers?appId=5&urn=123332 …

108723 application security

---

Dfe.Academies.External.Web/Pages/Index.cshtml

Content / text changes as per ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108990?McasTsid=26110
First page / home page / landing page content should look the same as screenshot on ticket
n/a
1. Open application and ensure  home page / landing page content looks the same as screenshot on ticket
n/a

108990 content changes home page

---

Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Enums/AcademisationWorkflowEnums.cs
Dfe.Academies.External.Web/Helpers/AadAuthorisationHelper.cs
Dfe.Academies.External.Web/Helpers/FileUploadConstants.cs
Dfe.Academies.External.Web/Middleware/BespokeExceptionHandlingMiddleware.cs
Dfe.Academies.External.Web/Models/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Models/SetAdditionalDetailsCommand.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml
Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_FileUploadPartial.cshtml
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/FileUploadService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/ResilientRequestProvider.cs
Dfe.Academies.External.Web/ViewModels/FileUploadViewModel.cs
Dfe.Academies.External.Web/ViewModels/FurtherInformationSectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/FurtherInformationSummaryViewModel.cs
Dfe.Academies.External.Web/appsettings.json
Dfe.Academies.External.Web/wwwroot/css/site.css

Resolves [#103694>](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=103694)
Further information summary page and the additional details page has been added, along with document upload
1. Go to the application summary page and click Further Information
2. You should be redirected to the Further Information Summary page
3. Clicking start section/change your answers should take you to the Additional Details page.
4. Clicking Save and Continue should save all the fields to the database and the documents should be in Sharepoint

103694 additional details page

---

Dfe.Academies.External.Web/Pages/Index.cshtml

To resolve test fail problems of this ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108990?McasTsid=26110
You must: / You should also: font size not as big as on figma design home / index / landing page
1. You must: / You should also: font size not as big as on figma design home / index / landing page
1. You must: / You should also: font size bigger on home / index / landing page
n/a

amended title font size

---

Dfe.Academies.External.Web.UnitTest/Pages/School/ApplicationSelectSchoolModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/Trust/ApplicationSchoolJoinAMatTrustSummaryModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/Trust/ApplicationSelectTrustModelTests.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/Base/BaseApplicationPageEditModel.cs
Dfe.Academies.External.Web/Pages/Base/BaseApplicationSummaryPageModel.cs
Dfe.Academies.External.Web/Pages/Trust/ApplicationSchoolJoinAMatTrustSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/ApplicationSchoolJoinAMatTrustSummary.cshtml.cs
Dfe.Academies.External.Web/ViewModels/ApplicationSchoolJoinAMatTrustSummaryViewModel.cs
Dfe.Academies.External.Web/ViewModels/SchoolPupilNumbersSummaryHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/SummaryPages/ApplicationSchoolJoinAMatTrustSummaryHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/SummaryPages/ApplicationSchoolJoinAMatTrustSummarySectionViewModel.cs

New page, see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/104657
1) trust link on application overview now goes to this new summary page
2) change link on this new page goes to select trust page
3) Other details change link now working yet as page doesn't exist yet
n/a
1) trust link on application overview now goes to this new summary page
2) change link on this new page goes to select trust page
3) Other details change link now working yet as page doesn't exist yet
n/a

104657 trust summary page

---

Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs

CSS styling not matching the ACs
1.
2.
3.
4.
1.
2.
3.
4.

Updated style changes for AdditionalDetails.cshtml

---

Dfe.Academies.External.Web/Pages/Index.cshtml

'Before you start' font still not big enough
1. 'Before you start' font still not big enough
1. 'Before you start' font might be big enough

amended font

---

Dfe.Academies.External.Web/Helpers/FileUploadConstants.cs
Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml.cs

Current financial year now has the ability to upload two supporting evidence docs
1.
2.
3.
4.
1.Go to the current financial year page for a school
2. select deficit for both options
3. upload docs
4. check that they are in SharePoint with the right prefix

AB#111385 upload current financial year docs

---

Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_FileUploadPartial.cshtml

Styling changes and a few persistence issues with the form not saving the state
1. Retest the additional details page
2.
3.
4.
1.
2.
3.
4.

Updated styling changes and school name not being populated

---

Dfe.Academies.External.Web/CustomValidators/AllowedExtensionAttribute.cs
Dfe.Academies.External.Web/CustomValidators/MaxFileSizeAttribute.cs
Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml.cs

- [*] New feature (non-breaking change which adds functionality)
1.
2.
3.
4.
1. Go to application school finance, any section, any upload 
2. try and upload a file that isn't valid file type
3. save 
4. error message is shown at the top of the page

111384 upload previous financial year docs

---

Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml.cs

Fixing document types for upload and back link to further information summary page
1.
2.
3.
4.
1.
2.
3.
4.

Updated back link and fixed the file type annotations

---

.github/workflows/dotnet.yml

Adds SonarCloud scanning to pull requests for the repo, including code coverage metrics

Add sonarcloud scanning

---

Dfe.Academies.External.Web/Pages/Error.cshtml

See ticket screenshot for new content:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/110373?McasTsid=26110
Content on error page should look like figma
1. Browse to https://localhost:44350/Error and check content vs ticket
1. Browse to https://localhost:44350/Error and check content vs ticket
n/a

content changes as per figma

---

Dfe.Academies.External.Web/Pages/School/Declaration.cshtml

Content changes as per ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/111918?McasTsid=26110
Content should be as per screenshot on ticket
1. Content wrong on declaration page
1. Go to application overview / declaration summary / change to view content changes
n/a

content changes as per ticket

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml

See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112704?McasTsid=26110
Amending top paragraph text to be in line with ticket
n/a
1.
n/a

application overview - amending top copy as per ticket

---

Dfe.Academies.External.Web/appsettings.json

See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112893?McasTsid=26110
new web app sentry DSN / URL configured
n/a
1. new web app sentry DSN / URL configured
n/a

amend sentry URL to newly configured one

---

Dfe.Academies.External.Web/Models/ConversionApplication.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs

See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107934?McasTsid=26110
On application overview page, add a contributor link shouldn't show until a school has been selected / added against the application
n/a
1. go to application overview where a school exists against the application, user should see add contributor link
2. go to application overview where NO school exists against the application, user should NOT see add contributor link
n/a

107934 - Application - Contributor - Email Notifications

---

.env.development.local.example
.github/workflows/continuous-integration-image-build-test.yml
.gitignore
Dockerfile
README.md
docker-compose.yml
script/web-docker-entrypoint.sh

* Adds a Dockerfile to build the dotnet application
* Adds a docker-compose.yml file to launch the required services for running the app locally
* This is the first step required to get the app running within a containerised environment (eg. Azure Container Apps)

Containerise with docker

---

Dfe.Academies.External.Web/Models/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Pages/School/Leases.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Loans.cshtml.cs

Loans and Leases now has nullable bool in the database to represent progress in these areas, null if the sections have not been started otherwise true or false. Implementation is not ideal, probably needs a rethink for 2.0
1.
2.
3.
4.
1. go to the loans and leases section within school finance
2. add loans
3. removed loans 
4. save and check values are consistent when the details are changed

AB#108901 - wired up hasLoans/hasLeases to api

---

Dfe.Academies.External.Web.UnitTest/Pages/AddAContributorModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/RemoveAContributorConfirmationModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/ConversionApplicationContributorViewModelTests.cs
Dfe.Academies.External.Web/Models/ConversionApplicationContributor.cs
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
Dfe.Academies.External.Web/Pages/RemoveAContributorConfirmation.cshtml
Dfe.Academies.External.Web/Pages/RemoveAContributorConfirmation.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_ApplicationContributorsPartial.cshtml
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs
Dfe.Academies.External.Web/ViewModels/ConversionApplicationContributorViewModel.cs

See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108413?McasTsid=26110
User can remove a contributor from invite contributors page
n/a
1. from your applications go into an application
2. go to invite contributors link at bottom of page
3. on invite contributors page there's a list of contributors at the bottom, alongside each one is remove link
4. click remove link, user show confirm page
5. click remove removes form API / DB
6. user sent back to invite contributors page, contributor will no longer exist
n/a

108413 remove a contributor

---

Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs

See below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113386?McasTsid=26110
Shouldn't be able to invite yourself as a contributor as you already have access!
1. go to application overview, invite a contributor, invite yourself
1. go to application overview, invite a contributor, invite yourself
n/a

invite a contributor - additional validation

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Declaration.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolJoinAMatTrustSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolLocalGovernanceArrangements.cshtml

see:-
Declaration page issue:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113777?McasTsid=26110
local government arrangements page issue:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113778?McasTsid=26110
trust summary page issue:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113779?McasTsid=26110
App overview issues:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112258?McasTsid=26110
see tickets
1. see tickets
1. see tickets
n/a

minor bugs x 4

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml

See below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112258?McasTsid=26110
some of:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112260?McasTsid=26110
1) "The trust the school will join" heading - font size
2) submit button - wrong text
3) non-chair submit warning in the wrong place
1. go to app overview to see minor styling differences
1. go to app overview to NOT see minor styling differences
n/a

3 application overview styling tweaks

---

Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustSummary.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/TrustComponentViewModel.cs

Resolves [106397](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=106397)
Form a mat trust summary page

Added form a mat trust summary page

---

Dfe.Academies.External.Web.UnitTest/Pages/ApplicationOverviewTests.cs
Dfe.Academies.External.Web/Models/SubmitApplicationCommand.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Leases.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs

Wire up submit application button to API and then show the submitted page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112260?McasTsid=26110
Wire up submit application button to API and then show the submitted page:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/112260?McasTsid=26110
n/a
1. go to application overview
2. if user = chair and everything has been filled in submit application button is visible
3. press submit button and ensure DB is updated and see submitted page
n/a

112260 wire up submit application

---

Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs

Resolves [114004](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=114004)
Fixed completed status displaying when the approvers email and full name aren't added to the conversion document
1.
2.
3.
4.
1.
2.
3.
4.

Added approvers full name and email address

---

Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummaryModelTests.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDateSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummary.cshtml.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustReasonsHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustReasonsSectionViewModel.cs

See ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107018
Create new Reasons for forming trust summary page
n/a
1. go to app overview FAM application
2. click on trust details
3. click on 'Reasons for forming the trust'
4. new summary page will show
n/a

107108 trust reasons summary

---

Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustGrowthSummaryModelTests.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGrowthSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGrowthSummary.cshtml.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustGrowthHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustGrowthSectionViewModel.cs

see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107020?McasTsid=26110
Build FAM 'plans for growth' summary page
n/a
1. go to app overview - FAM application
2. click on 'trust details'
3. click on 'plans for growth' - new page will be shown
n/a

Plans for growth (summary) page - 107020

---

Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategySummaryModelTests.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStategySummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategySummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategySummary.cshtml.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustImprovementStrategyHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustImprovementStrategySectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustOpeningDateHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustOpeningDateSectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustReasonsHeadingViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustReasonsSectionViewModel.cs
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/TrustComponentViewModel.cs

see ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/107022
Create new Trust School improvement strategy (summary) page - FAM
n/a
1. go to app overview - FAM application
2. click on 'trust details'
3. click on 'school improvement strategy' - new page will be shown
n/a

Trust School improvement strategy (summary) page - 107022

---

Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDateSummary.cshtml
Dfe.Academies.External.Web/ViewModels/TrustSummaryPages/ApplicationNewTrustOpeningDateSectionViewModel.cs

Resolves [#107013](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=107013)
Styling fixes on the form a mat opening date summary page
1.
2.
3.
4.
1.
2.
3.
4.

Fixed styling by adding details heading and changing display text

---

Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategyModelTests.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategy.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategy.cshtml.cs

Added trust improvement strategy page
1.
2.
3.
4.
1.Go to FAM application
2.Go to Trust Details
3. Select School improvement strategy
4.Follow the instructions on the page to fill in the details required

Trust improvement strategy

---

Dfe.Academies.External.Web.UnitTest/Models/NewTrustTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceStructureDetailsTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationCreationServiceTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceConversionStatusLogicTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceDeclarationStatusLogicTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ConversionApplicationRetrievalServiceTrustStatusLogicTests.cs
Dfe.Academies.External.Web/Helpers/FileUploadConstants.cs
Dfe.Academies.External.Web/Models/NewTrust.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceStructureDetails.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceStructureDetails.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/Services/FileUploadService.cs

Resolves [#107027](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=107027)
Governance structure details page and summary status logic
1.
2.
3.
4.
1. Go to the form a MAT details page
2. Navigate to the governance structure url
3. Can you upload a file?
4. Does the status update on the summary page if a file is present?
5.

107027 trust governance structure details page

---

Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationJoinTrustReasons.cshtml
Dfe.Academies.External.Web/Pages/School/Declaration.cshtml
Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml
Dfe.Academies.External.Web/Pages/School/PupilNumbers.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml
Dfe.Academies.External.Web/Pages/Shared/_ApplicationContributorsPartial.cshtml
Dfe.Academies.External.Web/Pages/Shared/_SchoolConversionComponentPartial.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolJoinAMatTrustSummary.cshtml
Dfe.Academies.External.Web/Pages/WhatIsYourRole.cshtml
Dfe.Academies.External.Web/Pages/YourApplications.cshtml

See below:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/114547?McasTsid=26110
Various bug fixes identified by sonar source
1. see ticket
1. see ticket
n/a

114547 - Fix sonar source identified bugs

---

Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustPlansForGrowth.cshtml

Resolves [#107021](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=107021)
Fixed the back link on the trust growth details page
1. Go the Form A Mat details page
2. Click on trust growth
3. Click on start section/change your answers
4. Click the back link
1.
2.
3.
4.

Fixed back link on FAM plans for growth

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs

Resolves [#114438](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=114438)
Fixed inset text on JAM application overview when application is completed and ready to be submitted
1. Go to JAM application overview
2. Is the insert text near the title?
3. Complete all the sections
4. Is it still there?
1.
2.
3.
4.

Removed inset text on JAM when application is completed

---

Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml

Changed the text on the school overview page when the application type is Form A Mat
1.
2.
3.
4.
1.
2.
3.
4.

Updated text on SchoolOverview.cshtml when the application is FAM

---

Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustSummary.cshtml

Changed trust overview button text

---

Dfe.Academies.External.Web/Pages/Base/BaseSchoolSummaryPageModel.cs
Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml.cs

Resolves [#113208](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=113208)
Fixed declaration text on school overview and designs on the page
1. Go to the FAM school overview page
2.
3.
4.
1.
2.
3.
4.

113208 fam school overview

---

Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustSummary.cshtml

Added missing text on FAM trust summary page
1.
2.
3.
4.
1.
2.
3.
4.

Added missing text

---

Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGrowthSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategySummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDateSummary.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasonsSummary.cshtml

Resolves [#115209](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=115209)
Fixed back link text for trust pages
1.
2.
3.
4.
1.
2.
3.
4.

Changed back link text to trust overview

---

terraform/container-apps-hosting.tf

- Patch to ensure terraform is aware of the CDN

Added missing line to ensure CDN creation

---

Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml.cs

Resolves [113208](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=113208)
Fixed non-chair of governors contributor being able to navigate to the declaration page on the FAM school overview
1.
2.
3.
4.
1.
2.
3.
4.

Fixed non-chair being able to complete the declaration page

---

terraform/README.md
terraform/container-apps-hosting.tf

- Contains a fix which creates the TLS validation TXT records and ALIAS records

Bump container app hosting module v0.10.2

---

Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs

see ticket:-
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/105861
axe & wave browser plugins showing critical / important issues that should be fixed
1. go to land & buildings summary page, run axe & wave browser plugins. Will show critical / important issues
1. go to land & buildings summary page, run axe & wave browser plugins. Will show no critical / important issues
n/a

105861 summary accessibility issues

---

Dfe.Academies.External.Web/Pages/School/SchoolOverview.cshtml.cs

Resolves [#116005](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Apply%20to%20become/Stories/?workitem=116005)
Revert previous change to hiding the declaration page for non-chair contributors
1.
2.
3.
4.
1.
2.
3.
4.

Reverted non-chair being unable to submit declaration

---

Dfe.Academies.External.Web.UnitTest/Pages/RemoveSchoolModelTests.cs
Dfe.Academies.External.Web/AcademiesAPIResponseModels/AddressResponse.cs
Dfe.Academies.External.Web/Models/DeleteSchoolCommand.cs
Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/RemoveSchool.cshtml
Dfe.Academies.External.Web/Pages/RemoveSchool.cshtml.cs
Dfe.Academies.External.Web/Pages/RemoveSchoolSelection.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs

See below ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/113359
User is able to remove a school from an application
n/a
1. Go to FAM App overview
2. Press remove school button
3. select school, press submit
4. press submit again
n/a

113359 remove school page

---

.github/workflows/cd-development.yml

Fix workflow tags

---

Dfe.Academies.External.Web/Pages/Shared/_SchoolConversionComponentPartial.cshtml

Fixed axe and wave serious issues with dt and dd tags

---

Dfe.Academies.External.Web/Pages/RemoveSchool.cshtml

Fixed minor ui issues

---

Dfe.Academies.External.Web/Pages/Base/BasePageEditModel.cs
Dfe.Academies.External.Web/Pages/Base/BaseSchoolSummaryPageModel.cs
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultationSummary.cshtml
Dfe.Academies.External.Web/Pages/School/DeclarationSummary.cshtml
Dfe.Academies.External.Web/Pages/School/FinancesReview.cshtml
Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml
Dfe.Academies.External.Web/Pages/School/LandAndBuildingsSummary.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml
Dfe.Academies.External.Web/Pages/Shared/_BackButton.cshtml
Dfe.Academies.External.Web/Pages/Shared/_BackButton.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_BackLink.cshtml
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/ViewModels/BackViewModel.cs

Fixed document upload status
1.
2.
3.
4.
1.
2.
3.
4.

Added return to school overview partial to the summary pages.

---

.github/workflows/build-and-push-image-development.yml

- Adds the final stage to the deployment workflow to automate the restart of the Azure Container App

Added container revision automation

---

Dfe.Academies.External.Web.UnitTest/AutoPopulatedMoqPropertiesCustomization.cs
Dfe.Academies.External.Web.UnitTest/Automapper/AutoMapperSetupTests.cs
Dfe.Academies.External.Web.UnitTest/Dfe.Academies.External.Web.UnitTest.csproj
Dfe.Academies.External.Web.UnitTest/PropertiesPostprocessor.cs
Dfe.Academies.External.Web/AutoMapper/AutoMapperProfile.cs
Dfe.Academies.External.Web/AutoMapper/AutoMapperSetup.cs
Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Dtos/EmailVariablesDto.cs
Dfe.Academies.External.Web/Factories/ContributorNotifyTemplateFactory.cs
Dfe.Academies.External.Web/Factories/IContributorNotifyTemplateFactory.cs
Dfe.Academies.External.Web/Helpers/NotifyTemplateSettings.cs
Dfe.Academies.External.Web/Models/EmailTemplates/FormAMatChairContributor.cs
Dfe.Academies.External.Web/Models/EmailTemplates/FormAMatNonChairContributor.cs
Dfe.Academies.External.Web/Models/EmailTemplates/IContributorTemplate.cs
Dfe.Academies.External.Web/Models/EmailTemplates/IEmailTemplate.cs
Dfe.Academies.External.Web/Models/EmailTemplates/JoinAMatChairContributor.cs
Dfe.Academies.External.Web/Models/EmailTemplates/JoinAMatNonChairContributor.cs
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/Services/ContributorEmailSenderService.cs
Dfe.Academies.External.Web/Services/IContributorEmailSenderService.cs
Dfe.Academies.External.Web/appsettings.json

Refactored email service and added join a mat templating

---

Dfe.Academies.External.Web/Program.cs

118700 redirect overrride

---

Dfe.Academies.External.Web/Program.cs

118700 redirect override cookie fix

---

.github/workflows/build-and-push-image-test.yml

- Automates the restart of the container after the image build completes

Automate deployment for Test environment

---

Dfe.Academies.External.Web/Pages/YourApplications.cshtml

Fixed page text

---

Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/appsettings.json

Added application insights config to frontend

---

Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceStructureDetails.cshtml.cs
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/appsettings.Development.json
Dfe.Academies.External.Web/appsettings.Staging.json

Removed sentry logging

---

Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/appsettings.json

Reverted cookie policy changes and sentry appsettings block

---

Dfe.Academies.External.Web/Program.cs

Reverted cookie changes

---

Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Program.cs
Dfe.Academies.External.Web/appsettings.Development.json
Dfe.Academies.External.Web/appsettings.json

Added local development flag and azure blob storage creation

---

Dfe.Academies.External.Web/Program.cs

Changed blob storage retrieval to use the blob container client

---

Dfe.Academies.External.Web/Controllers/CookiesController.cs

Using local direct method to remove malicious vulnerability

---

terraform/README.md
terraform/container-apps-hosting.tf

This PR includes bug fixes for the Terraform module, where Container Apps were not being successfully restarted in a Github workflow

Updated Terraform module to v0.14.3

---

Dfe.Academies.External.Web/Helpers/FileUploadConstants.cs
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceStructureDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustGovernanceSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolJoinAMatTrustSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolTrustConsent.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs

Files should appear for schools after data migration
1. go to a school page that has a file upload
2. check the file is there
3. no file
4.
1. go to a school page that has a file upload
2. check the file is there
3. file should now be there
4.

Changed the path that files are expected to be for schools

---

Dfe.Academies.External.Web/Program.cs

IT Health Check missing content security header
1.
2.
3.
4.
1.
2.
3.
4.

Ithc fixes

---

Dfe.Academies.External.Web/Jobs/FixSharepointFoldersJob.cs
Dfe.Academies.External.Web/Services/FileUploadService.cs

Added more logging to sharepoint API calls

---

Dfe.Academies.External.Web/Commands/SetAdditionalDetailsCommand.cs
Dfe.Academies.External.Web/Dtos/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/IConversionApplicationCreationService.cs

Removed safeguarding text box and replaced with boolean value

---

Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml
Dfe.Academies.External.Web/Pages/School/Leases.cshtml
Dfe.Academies.External.Web/Pages/School/Loans.cshtml
Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml

Fixed back link functionality in finance pages

---

Dfe.Academies.External.Web.UnitTest/Pages/WhatAreYouApplyingToDoModelTests.cs
Dfe.Academies.External.Web.UnitTest/Pages/WhatIsYourRoleModelTests.cs
Dfe.Academies.External.Web.UnitTest/Services/TempDataHelperServiceTests.cs
Dfe.Academies.External.Web.UnitTest/Services/ViewDataHelperTests.cs
Dfe.Academies.External.Web/Pages/WhatAreYouApplyingToDo.cshtml.cs
Dfe.Academies.External.Web/Pages/WhatIsYourRole.cshtml.cs
Dfe.Academies.External.Web/Services/TempDataHelper.cs

Logging added to help troubleshoot form a mat bug

added logging to workout issue with form a mat applications

---

terraform/README.md
terraform/container-apps-hosting.tf
terraform/locals.tf
terraform/variables.tf

- Adds Terraform option to deploy a Azure Cache for Redis instance

Deploy Redis cache

---

Dfe.Academies.External.Web.UnitTest/Pages/ApplicationOverviewTests.cs
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs

Added logging to application overview page to identify contributor bug

AB#120676 - Added logging

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs

Fix for not finding the contributor and role associated to said user causing page to be shown in wrong state (non chair)

possible fix for not finding right user

---

Dfe.Academies.External.Web/Pages/Accessibility-Statement.cshtml

target to hyper link as  requested added as requested.

new tab for hyperlink

---

Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolChangesToATrust.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolLocalGovernanceArrangements.cshtml

updated the razor pages so step 3 back button goes back to step 2
ApplicationSchoolLocalGovernanceArrangements goes back to ApplicationSchoolChangesToATrust
and step 2 back button goes to step 1
ApplicationSchoolChangesToATrust goes back to ApplicationSchoolTrustConsent

back button fixes

---

Dfe.Academies.External.Web/Pages/Accessibility-Statement.cshtml

target fix

---

Dfe.Academies.External.Web/Pages/Help/Help.cshtml
Dfe.Academies.External.Web/Pages/Shared/_Layout.cshtml
Dfe.Academies.External.Web/Program.cs

this is a change to the existing phase banner
it redirects to a temporary placeholder help page for further development

122863 update help phase banner

---

Dfe.Academies.External.Web.UnitTest/Pages/CookiesModelTests.cs
Dfe.Academies.External.Web/Controllers/CookiesController.cs
Dfe.Academies.External.Web/Middleware/ResponseHeadersMiddleWare.cs
Dfe.Academies.External.Web/Pages/Cookies.cshtml
Dfe.Academies.External.Web/Pages/Cookies.cshtml.cs
Dfe.Academies.External.Web/Pages/Shared/_CookieConsentPartial.cshtml
Dfe.Academies.External.Web/Pages/Shared/_Footer.cshtml

Removal of google cookies (hopefully) add logging to help if not and redirect from cookies page made relative

92474 cookie consent page

---

Dfe.Academies.External.Web/Pages/Help/Problem.cshtml

changes to the problem page to make it gds compliant

problem page changes

---

Dfe.Academies.External.Web/Pages/Help/HowCanWeHelp.cshtml
Dfe.Academies.External.Web/Pages/Shared/_Layout.cshtml

changes to html to ensure accessibility issues are fixed on how can we help page
grey text added to below radio buttons on  how can we help page
bux fix for 126659
[Bug 126659](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/126659): Dev: Hide New Help Banner On Homepage

bux fixes and phase banner logic

---

Dfe.Academies.External.Web/Pages/Help/ApplicationHelp.cshtml
Dfe.Academies.External.Web/Pages/Help/Problem.cshtml

removed javascript aspect of character count on text area

removed javascript aspect of character count on text area

---

Dfe.Academies.External.Web/Enums/HelpWorkflowEnums.cs
Dfe.Academies.External.Web/Helpers/NotifyTemplateSettings.cs
Dfe.Academies.External.Web/Pages/Help/Feedback.cshtml
Dfe.Academies.External.Web/Pages/Help/Feedback.cshtml.cs
Dfe.Academies.External.Web/appsettings.json

feedback page added
can accept up to 2000 characters
email integration and feedback template added

feedback page with email integration

---

Dfe.Academies.External.Web/Pages/Help/ApplicationHelp.cshtml.cs
Dfe.Academies.External.Web/Pages/Help/Problem.cshtml.cs
Dfe.Academies.External.Web/Pages/Help/ThankYou.cshtml
Dfe.Academies.External.Web/Pages/Help/ThankYou.cshtml.cs

122817 help with application

---

Dfe.Academies.External.Web/Pages/Help/Feedback.cshtml

accessibility bug fixes on feedback page

122818 feedback accesibility fixes

---

Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml
Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml
Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml
Dfe.Academies.External.Web/Pages/School/LeaseDetails.cshtml
Dfe.Academies.External.Web/Pages/School/LoanDetails.cshtml
Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustImprovementStrategy.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustKeyPerson.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustPlansForGrowth.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustReasons.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolChangesToATrust.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolLocalGovernanceArrangements.cshtml

text box increase (2000 characters)

127679 text boxes

---

Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustKeyPerson.cshtml

cosmetic fix to the trust key people page

Key people - save button bug

---

Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/School/NextFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/School/PreviousFinancialYear.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustKeyPerson.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolChangesToATrust.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolTrustConsent.cshtml

remaining validation fixes plus bug fixes

futher validation fixes

---

Dfe.Academies.External.Web/Pages/School/CurrentFinancialYear.cshtml

file upload fix on current financial yea

work file type fix

---

Dfe.Academies.External.Web.UnitTest/Pages/School/SchoolMainContactsModelTests.cs
Dfe.Academies.External.Web.UnitTest/ViewModels/ApplicationSchoolContactsViewModelTests.cs
Dfe.Academies.External.Web/Pages/School/SchoolConversionKeyDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml
Dfe.Academies.External.Web/Pages/School/SchoolMainContacts.cshtml.cs
Dfe.Academies.External.Web/ViewModels/ApplicationSchoolContactsViewModel.cs

telephone numbers removed from main contacts page and summary page

telephone numbers removed from contact

---

Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustPlansForGrowth.cshtml
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustPlansForGrowth.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolLocalGovernanceArrangements.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolLocalGovernanceArrangements.cshtml.cs

default radio button fixed on trust journeys
plans for growth page
local governance page

127457 default radio buttons trust journey

---

Dfe.Academies.External.Web.UnitTest/Dfe.Academies.External.Web.UnitTest.csproj
Dfe.Academies.External.Web.UnitTest/Services/ResilientRequestProviderTests.cs
Dfe.Academies.External.Web/Dfe.Academies.External.Web.csproj
Dfe.Academies.External.Web/Dtos/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Pages/Base/BasePageModel.cs
Dfe.Academies.External.Web/Pages/Help/ApplicationHelp.cshtml.cs
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml
Dfe.Academies.External.Web/Pages/School/AdditionalDetails.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationConversionTargetDate.cshtml.cs
Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationSchoolConsultation.cshtml.cs
Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml
Dfe.Academies.External.Web/Pages/School/FinancialInvestigations.cshtml.cs
Dfe.Academies.External.Web/Pages/School/FurtherInformationSummary.cshtml.cs
Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml
Dfe.Academies.External.Web/Pages/School/LandAndBuildings.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Leases.cshtml
Dfe.Academies.External.Web/Pages/School/Leases.cshtml.cs
Dfe.Academies.External.Web/Pages/School/Loans.cshtml
Dfe.Academies.External.Web/Pages/School/Loans.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/FormAMat/ApplicationNewTrustOpeningDate.cshtml.cs
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSchoolChangesToATrust.cshtml.cs
Dfe.Academies.External.Web/Services/ConversionApplicationCreationService.cs
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/Services/ReferenceDataRetrievalService.cs
Dfe.Academies.External.Web/Services/ResilientRequestProvider.cs

radio buttons now have a default of no selection, validation fixes to go with it

124884 radio button defaults school

---

Dfe.Academies.External.Web/Pages/School/ApplicationChangeSchoolName.cshtml

validation styling and behaviour fix

129162 bug fix radio button defaults change school name

---

.github/workflows/build-and-push-image.yml

Enables cypress tests on deploy action

Adding back cypress tests to deploy action

---

Dfe.Academies.External.Web.UnitTest/Pages/AddAContributorModelTests.cs
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml
Dfe.Academies.External.Web/Pages/AddAContributor.cshtml.cs
Dfe.Academies.External.Web/Pages/RemoveAContributorConfirmation.cshtml
Dfe.Academies.External.Web/Pages/RemoveAContributorConfirmation.cshtml.cs

- Minor content/wording change on remove a contributor
- [A2B] Invite a contributor Page - Remove a Contributor Success Banner

AB#129536-content change on remove a contributor

---

.github/workflows/dotnet.yml

Added dfe nuget package source

added dfe nuget package source

---

.github/workflows/build-and-push-image.yml
Dfe.Academies.External.Web/CypressTests/README.md
Dfe.Academies.External.Web/CypressTests/cypress.config.ts
Dfe.Academies.External.Web/CypressTests/package.json
README.md

Updates the documentation around the Cypress tests and disables video recording to reduce execution time
N/A
N/A
N/A

Updated docs for Cypress, disabled video recording

---

Dfe.Academies.External.Web/CypressTests/docker-compose.yml

Fix path on volume mount to report directory

Hotfix Update Cypress docker-compose.yml

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml
Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml.cs
Dfe.Academies.External.Web/Pages/DeleteApplication.cshtml
Dfe.Academies.External.Web/Pages/DeleteApplication.cshtml.cs

delete application page added
logic around only lead contributor only being able to delete
delete functionality doesn't work atm that is the next bit of work to be added

delete application page and logic

---

Dfe.Academies.External.Web/Helpers/NotifyTemplateSettings.cs
Dfe.Academies.External.Web/Pages/DeleteApplication.cshtml.cs
Dfe.Academies.External.Web/appsettings.json

email notification added to delete functionality
template ids added

133684 emailnotifications

---

Dfe.Academies.External.Web/CypressTests/cypress/e2e/deleteNewJAMApp.spec.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BConfirmApplicationDelete.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BYourApplication.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BYourApplications.ts
Dfe.Academies.External.Web/CypressTests/cypress/support/commands.ts
Dfe.Academies.External.Web/CypressTests/package-lock.json

Added a new DeleteJAMApp test, page object for the Delete page, and commands.ts function to verifyElementsVisible()

Delete applications auto

---

Dfe.Academies.External.Web/Pages/Shared/_ApplicationContributorsPartial.cshtml

fix to  lead contributor issue

prevent lead contributor

---

Dfe.Academies.External.Web/Pages/Shared/_ApplicationContributorsPartial.cshtml

133684 deleteleadcontributorfixfurtherfix

---

Dfe.Academies.External.Web/Pages/Shared/_ApplicationContributorsPartial.cshtml

133684 deleteleadcontributorfixfurtherchangeinlogic

---

Dfe.Academies.External.Web/Pages/Shared/_ApplicationContributorsPartial.cshtml

removal of lead contributor label

remove lead contributor

---

Dfe.Academies.External.Web/CypressTests/cypress/support/commands.ts

Hey Dan,
Please find the changes to commands.ts as specified before in out Slack chat.
Many thanks

Content change auto

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml

link text change

---

Dfe.Academies.External.Web/Pages/Help/ApplicationHelp.cshtml
Dfe.Academies.External.sln
release-notes.md

fix headers on help page, remove hint text and replaced with header label

#134541 fix help page headers

---

Dfe.Academies.External.Web/Pages/Help/ApplicationHelp.cshtml
Dfe.Academies.External.Web/Pages/Help/ApplicationHelp.cshtml.cs
Dfe.Academies.External.Web/appsettings.json

radios added for app reference selection
email notifications updated to include application reference number

add applicationreference number to help query

---

Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewFAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/fixtures/data-generator.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMGovernanceStructureDetails.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMGovernanceStructureSummary.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMKeyPeopleSummary.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMKeyPersonDetails.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMPlansForGrowthDetails.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMPlansForGrowthSummary.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMReasonsForFormingTrustDetails.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMReasonsForFormingTrustSummary.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMSchoolImprovementStrategyDetails.ts.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMSchoolImprovementStrategySummary.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMSchoolOverview.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMTrustOpeningDateDetails.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMTrustOpeningDateSummary.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMTrustOverview.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BFAMTrustname.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BPre-openingSupportGrantDetails.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BWhatAreYouApplyingToDo.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/A2BYourApplication.ts
Dfe.Academies.External.Web/CypressTests/cypress/support/commands.ts
Dfe.Academies.External.Web/CypressTests/package-lock.json
Dfe.Academies.External.Web/CypressTests/package.json

Looking to add changes made to allow the introduction of the automation of Creating a new FAM app and submitting.
Many thanks

Create new fam app

---

Dfe.Academies.External.Web/CypressTests/cypress/support/commands.ts

Updated Accessiblity tests to also include WCAG 2.1

Dfe.Academies.External.Web/CypressTests/cypress/support/commands.ts

---

.github/workflows/build-and-push-image.yml
.github/workflows/dotnet.yml
.github/workflows/security-tests.yml

Bumps actions versions to remove node 16 deprecation warnings

Bump azure actions to v2

---

.github/workflows/build-and-push-image.yml

> invalid tag "ghcr.io/DFE-Digital/Dfe.Academies.External:master": repository name must be lowercase

Fix: Set GHCR repository name to lower case

---

.github/workflows/build-and-push-image.yml

* Adds missing `steps` on acr-import job

Fix build-and-push workflow

---

.github/workflows/build-and-push-image.yml

Fix acr import command in workflow

---

.github/workflows/build-and-push-image.yml

* `do` needs to be on a new line

Fix acr import for loop in workflow

---

.github/workflows/build-and-push-image.yml

* A different set of credentials are needed for the acr import. This has been added as a new secret `ACR_CREDENTIALS`

Use ACR credentials for acr import

---

.github/workflows/build-and-push-image.yml

* Need to replace `source` with `tag`

Fix tags for loop in acr-import job

---

.github/workflows/build-and-push-image.yml

* Pushing to GHCR and Importing from ACR has been tested on the development environment. This modifies the workflow so that it will run on the other environments.

Modify build and push workflow for all environments

---

.github/workflows/build-and-push-image.yml

* This is only set up for development whilst we test the changes
After a deployment to the 'Development' environment has been completed, an annotation should be added to App Insights to mark the release in the timeline
1. Deploy a release to Development
2. View the associated App Insights instance 
3. See an annotation on the transaction timeline

Annotate App Insights after each release

---

.github/workflows/docker-build.yml

CI test for when the Dockerfile changes so we can ensure the image will build

Test the docker build if the Dockerfile changes

---

terraform/README.md
terraform/data-protection.tf

Ensures the Container App's user-assigned managed identity will be always granted the necessary Role Assignment to access the Key Vault that holds the Data Protection Keys

Automatically set Role Assignment for the Container App UAMI

---

terraform/README.md
terraform/data-protection.tf

* Sets an expiry date on Key Vault Keys
* Enables Diagnostic Audit Logs for Key Vault

Update Data Protection module to v1.1.0

---

Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/login.ts

Fixed issue with the password to run cypress tests.

fixed password login issue

---

Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewFAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewJAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/application.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/fam/schoolOverview.ts
Dfe.Academies.External.Web/Dtos/SchoolApplyingToConvert.cs
Dfe.Academies.External.Web/Helpers/UriFormatter.cs
Dfe.Academies.External.Web/Pages/Index.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrant.cshtml
Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml
Dfe.Academies.External.Web/Pages/School/Declaration.cshtml
Dfe.Academies.External.Web/Services/ConversionApplicationRetrievalService.cs
Dfe.Academies.External.Web/ViewModels/ApplicationPreOpeningSupportGrantHeadingViewModel.cs

Changed Grant Name from Pre-opening to Conversion and updated cypress tests

Changed Grant Name from Pre-opening to Conversion

---

Dfe.Academies.External.Web.UnitTest/Dfe.Academies.External.Web.UnitTest.csproj
Dfe.Academies.External.Web.UnitTest/ExpectedSecurityConfig.json
Dfe.Academies.External.Web.UnitTest/Pages/PageSecurityTests.cs
Dfe.Academies.External.Web/Program.cs

Validate all FE points are protected with anonymous FE endpoints.  

---

Dfe.Academies.External.Web/CypressTests/cypress/e2e/accessibilityTesting.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewFAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewJAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/e2e/deleteNewJAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/e2e/inviteAndRemoveContributor.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/login.ts
Dfe.Academies.External.Web/CypressTests/package.json

FIxed A2B tests for the pipeline.
All fixed except accessibility issues which we know about.

Auto a2b stuff

---

Dfe.Academies.External.Web/Pages/ApplicationOverview.cshtml

Don't Display Important banner if app status is submitted.

No banner display if app is submitted

---

Dfe.Academies.External.Web/Pages/School/ApplicationSelectSchool.cshtml
Dfe.Academies.External.Web/Pages/Trust/JoinAMat/ApplicationSelectTrust.cshtml

Fixed AXE issues

---

.github/workflows/cypress-tests.yml
Dfe.Academies.External.Web/CypressTests/cypress.config.ts
Dfe.Academies.External.Web/CypressTests/package-lock.json
Dfe.Academies.External.Web/CypressTests/package.json

* This will route the result of the Cypress tests into a Slack channel

Add Cypress Notifier task to Workflow

---

terraform/.terraform.lock.hcl
terraform/README.md
terraform/container-apps-hosting.tf
terraform/data-protection.tf
terraform/key-vault-tfvars-secrets.tf
terraform/statuscake-tls-monitor.tf
terraform/versions.tf

* Updated to latest Terraform module versions

Stabilised version constraints

---

Dfe.Academies.External.Web/CypressTests/cypress/cypress.config.js
Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewFAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/e2e/createNewJAMApp.cy.ts
Dfe.Academies.External.Web/CypressTests/cypress/page-objects/pages/fam/schoolOverview.ts

Fix A2B JAM And FAM Journeys to Use Post-midnight config in Dev and Test

Test dg post midnight jam fam journeys

---

Dfe.Academies.External.Web/Pages/School/ApplicationPreOpeningSupportGrantSummary.cshtml

Resolved - Banner will only display if the app is InProgress and grant is expired.

Removed banner after submitting the app

---

Dfe.Academies.External.Web/CypressTests/cypress/e2e/inviteAndRemoveContributor.cy.ts

Sorry guys, culled a load of applications in Test for the InviteContributor test.
This'll fix it in the Test environment 👍

if environment URL contains 'test' use applicationId 10492

---

.github/workflows/build-and-push-image.yml
renovate.json

- Updated renovate config to use the shared config.
- Added package validation workflow step

Updated renovate config to use the shared config - Added package validation workflow step

---

Dockerfile

**What is the change?**
Tidies up the syntax in the Dockerfile
**Why do we need the change?**
Reduces file operations and the number of layers in the final docker build
**What is the impact?**
Faster docker builds, and better dependency tracking from Renovate
**Azure DevOps Ticket**
N/A

Simplified syntax and reduced docker layers

---

.github/workflows/dotnet.yml

This workflow will become a required quality gate so we need to remove the path restrictions

Run .NET gate on every push/pull request
